from django.urls import path
from django.views.generic import RedirectView

from . import (
    api_views,
    api_views_integration,
    views,
    views_dadata,
    views_deploy,
    views_public,
    views_qr,
    views_uzhv_wizard,
)

urlpatterns = [
    path("internal/deploy/", views_deploy.deploy_webhook, name="deploy-webhook"),
    # Остатки демо-шаблона Materio (часто попадают в ?next= после входа)
    path("index/", RedirectView.as_view(pattern_name="platform-home", permanent=False)),
    path("dashboard/", RedirectView.as_view(pattern_name="platform-dashboard", permanent=False)),
    path("dashboard/crm/", RedirectView.as_view(pattern_name="platform-dashboard", permanent=False)),
    path("dashboard/analytics/", RedirectView.as_view(pattern_name="platform-home", permanent=False)),
    path("auth/login/", views.LoginView.as_view(), name="login"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("auth/sso/<int:pk>/start/", views.SsoLoginStartView.as_view(), name="sso-start"),
    path("auth/sso/callback/", views.SsoCallbackView.as_view(), name="sso-callback"),
    path("auth/2fa/verify/", views.TwoFactorVerifyView.as_view(), name="two-factor-verify"),
    path("auth/2fa/setup/", views.TwoFactorSetupView.as_view(), name="two-factor-setup"),
    path("auth/reauth/", views.ReauthConfirmView.as_view(), name="reauth-confirm"),
    path(
        "workspace/cabinet/security/2fa/disable/",
        views.TwoFactorDisableView.as_view(),
        name="two-factor-disable",
    ),
    path("switch-subsystem/", views.switch_subsystem, name="platform-switch-subsystem"),
    path("", views.HomeView.as_view(), name="platform-home"),
    path("acceptance/", views.AcceptanceView.as_view(), name="platform-acceptance"),
    path("docs/tz/download/", views.tz_download, name="platform-tz-download"),
    # M01
    path("administration/subsystems/", views.SubsystemsListView.as_view(), name="platform-subsystems"),
    path(
        "administration/subsystems/new/",
        views.SubsystemWizardCreateView.as_view(),
        name="platform-subsystem-create",
    ),
    path(
        "administration/subsystems/<int:pk>/modal/",
        views.SubsystemModalView.as_view(),
        name="platform-subsystem-modal",
    ),
    path(
        "administration/subsystems/<int:pk>/edit/",
        views.SubsystemUpdateView.as_view(),
        name="platform-subsystem-edit",
    ),
    path(
        "administration/subsystems/<int:pk>/publish/",
        views.SubsystemPublishView.as_view(),
        name="platform-subsystem-publish",
    ),
    path(
        "administration/subsystems/<int:pk>/archive/",
        views.SubsystemArchiveView.as_view(),
        name="platform-subsystem-archive",
    ),
    path(
        "administration/subsystems/<int:pk>/clone/",
        views.SubsystemCloneView.as_view(),
        name="platform-subsystem-clone",
    ),
    path(
        "administration/modules/toggle/<int:pk>/",
        views.SubsystemModuleToggleView.as_view(),
        name="platform-module-toggle",
    ),
    path("administration/modules/", views.ModuleCatalogAdminView.as_view(), name="platform-modules"),
    path(
        "administration/modules/<int:pk>/modal/",
        views.ModuleCatalogModalView.as_view(),
        name="platform-module-modal",
    ),
    path("administration/audit/", views.AuditLogAdminView.as_view(), name="platform-audit"),
    path(
        "administration/audit/export.csv",
        views.AuditLogExportView.as_view(),
        name="platform-audit-export",
    ),
    path(
        "administration/audit/<int:pk>/modal/",
        views.AuditLogModalView.as_view(),
        name="platform-audit-modal",
    ),
    path(
        "administration/audit/snapshot/",
        views.AuditSnapshotCreateView.as_view(),
        name="platform-audit-snapshot",
    ),
    # M02-M04
    path("administration/users/", views.UsersAdminView.as_view(), name="platform-users"),
    path("administration/users/new/", views.UserWizardCreateView.as_view(), name="platform-user-create"),
    path(
        "administration/users/<int:pk>/modal/",
        views.UserModalView.as_view(),
        name="platform-user-modal",
    ),
    path(
        "administration/users/<int:pk>/edit/",
        views.UserUpdateView.as_view(),
        name="platform-user-edit",
    ),
    path(
        "administration/users/<int:pk>/delete/",
        views.UserDeleteView.as_view(),
        name="platform-user-delete",
    ),
    path("administration/roles/", views.RolesListView.as_view(), name="platform-roles"),
    path("administration/roles/new/", views.RoleWizardCreateView.as_view(), name="platform-role-create"),
    path("administration/roles/<int:pk>/modal/", views.RoleModalView.as_view(), name="platform-role-modal"),
    path("administration/roles/<int:pk>/edit/", views.RoleUpdateView.as_view(), name="platform-role-edit"),
    path("administration/roles/<int:pk>/delete/", views.RoleDeleteView.as_view(), name="platform-role-delete"),
    path("administration/roles/<int:pk>/copy/", views.RoleCopyView.as_view(), name="platform-role-copy"),
    path("administration/structure/", views.StructureAdminView.as_view(), name="platform-structure"),
    path(
        "administration/structure/departments/new/",
        views.DepartmentWizardView.as_view(),
        name="platform-department-create",
    ),
    path(
        "administration/structure/departments/<int:pk>/modal/",
        views.DepartmentModalView.as_view(),
        name="platform-department-modal",
    ),
    path(
        "administration/structure/departments/<int:pk>/edit/",
        views.DepartmentUpdateView.as_view(),
        name="platform-department-edit",
    ),
    path(
        "administration/structure/departments/<int:pk>/delete/",
        views.DepartmentDeleteView.as_view(),
        name="platform-department-delete",
    ),
    path(
        "administration/structure/positions/<int:pk>/modal/",
        views.PositionModalView.as_view(),
        name="platform-position-modal",
    ),
    path(
        "administration/structure/positions/new/",
        views.PositionCreateView.as_view(),
        name="platform-position-create",
    ),
    path(
        "administration/structure/positions/<int:pk>/edit/",
        views.PositionUpdateView.as_view(),
        name="platform-position-edit",
    ),
    path(
        "administration/structure/positions/<int:pk>/delete/",
        views.PositionDeleteView.as_view(),
        name="platform-position-delete",
    ),
    # M07-M14
    path("workspace/cabinet/", views.CabinetAccountView.as_view(), name="platform-cabinet"),
    path("workspace/cabinet/security/", views.CabinetSecurityView.as_view(), name="platform-cabinet-security"),
    path(
        "workspace/cabinet/security/sessions/revoke/",
        views.CabinetSessionRevokeView.as_view(),
        name="platform-cabinet-session-revoke",
    ),
    path(
        "workspace/cabinet/delegations/create/",
        views.CabinetDelegationCreateView.as_view(),
        name="platform-cabinet-delegation-create",
    ),
    path(
        "workspace/cabinet/delegations/revoke/",
        views.CabinetDelegationRevokeView.as_view(),
        name="platform-cabinet-delegation-revoke",
    ),
    path("workspace/cabinet/billing/", views.CabinetBillingView.as_view(), name="platform-cabinet-billing"),
    path("workspace/cabinet/access/", views.CabinetAccessView.as_view(), name="platform-cabinet-notifications"),
    path("workspace/cabinet/connections/", views.CabinetConnectionsView.as_view(), name="platform-cabinet-connections"),
    path("workspace/cabinet/uzhv-push/", views.CabinetUzhvPushView.as_view(), name="platform-cabinet-uzhv-push"),
    path("workspace/cabinet/uzhv-push/test/", views.CabinetUzhvPushTestView.as_view(), name="platform-cabinet-uzhv-push-test"),
    path("workspace/cabinet/preferences/", views.CabinetPrefsView.as_view(), name="platform-cabinet-prefs"),
    path("help/", views.HelpCenterView.as_view(), name="platform-help-center"),
    path("workspace/today/", views.TodayView.as_view(), name="platform-today"),
    path(
        "workspace/today/widgets/",
        views.TodayWidgetsSaveView.as_view(),
        name="platform-today-widgets-save",
    ),
    path("workspace/tasks/new/", views.TaskCreateView.as_view(), name="platform-task-create"),
    path("workspace/tasks/form/", views.TaskFormModalView.as_view(), name="platform-task-form-modal"),
    path(
        "workspace/tasks/<int:pk>/form/",
        views.TaskFormModalView.as_view(),
        name="platform-task-form-modal-edit",
    ),
    path("workspace/tasks/<int:pk>/", views.TaskUpdateView.as_view(), name="platform-task-edit"),
    path("workspace/tasks/<int:pk>/modal/", views.TaskModalView.as_view(), name="platform-task-modal"),
    path("workspace/tasks/<int:pk>/complete/", views.TaskCompleteView.as_view(), name="platform-task-complete"),
    path("workspace/calendar/", views.CalendarView.as_view(), name="platform-calendar"),
    path("workspace/kanban/", views.KanbanView.as_view(), name="platform-kanban"),
    path("workspace/kanban/move/<int:pk>/", views.KanbanMoveView.as_view(), name="platform-kanban-move"),
    path("workspace/gantt/", views.GanttView.as_view(), name="platform-gantt"),
    path("workspace/favorites/", views.FavoritesView.as_view(), name="platform-favorites"),
    path("workspace/favorites/<int:pk>/delete/", views.FavoriteDeleteView.as_view(), name="platform-favorite-delete"),
    path(
        "workspace/filters/<int:pk>/delete/",
        views.SavedFilterDeleteView.as_view(),
        name="platform-saved-filter-delete",
    ),
    # M22
    path("cases/", views.CaseListView.as_view(), name="platform-cases"),
    path("cases/new/", views.CaseWizardCreateView.as_view(), name="platform-case-create"),
    path("cases/<int:pk>/", views.CaseDetailView.as_view(), name="platform-case-detail"),
    path("cases/<int:pk>/modal/", views.CaseModalView.as_view(), name="platform-case-modal"),
    path("cases/<int:pk>/edit/", views.CaseUpdateView.as_view(), name="platform-case-edit"),
    path("cases/<int:pk>/status/", views.CaseStatusView.as_view(), name="platform-case-status"),
    path("cases/<int:pk>/archive/", views.CaseArchiveView.as_view(), name="platform-case-archive"),
    path("cases/<int:pk>/comment/", views.CaseCommentView.as_view(), name="platform-case-comment"),
    path("cases/bulk/", views.CaseBulkView.as_view(), name="platform-cases-bulk"),
    path("bpm/tasks/<int:pk>/decide/", views.CaseBpmDecisionView.as_view(), name="platform-bpm-decide"),
    # M23
    path("registries/", views.RegistriesListView.as_view(), name="platform-registries"),
    path("registries/new/", views.RegistryTypeWizardView.as_view(), name="platform-registry-type-create"),
    path("registries/types/<int:pk>/modal/", views.RegistryTypeModalView.as_view(), name="platform-registry-type-modal"),
    path("registries/types/<int:pk>/edit/", views.RegistryTypeUpdateView.as_view(), name="platform-registry-type-edit"),
    path("registries/<int:type_pk>/", views.RegistryRecordsView.as_view(), name="platform-registry-records"),
    path(
        "registries/<int:type_pk>/records/form/",
        views.RegistryRecordFormModalView.as_view(),
        name="platform-registry-record-form-modal",
    ),
    path(
        "registries/<int:type_pk>/records/<int:pk>/form/",
        views.RegistryRecordFormModalView.as_view(),
        name="platform-registry-record-form-modal-edit",
    ),
    path(
        "registries/<int:type_pk>/records/new/",
        views.RegistryRecordCreateView.as_view(),
        name="platform-registry-record-create",
    ),
    path(
        "registries/<int:type_pk>/records/<int:pk>/modal/",
        views.RegistryRecordModalView.as_view(),
        name="platform-registry-record-modal",
    ),
    path(
        "registries/<int:type_pk>/records/<int:pk>/edit/",
        views.RegistryRecordUpdateView.as_view(),
        name="platform-registry-record-edit",
    ),
    path(
        "registries/<int:type_pk>/records/<int:pk>/delete/",
        views.RegistryRecordDeleteView.as_view(),
        name="platform-registry-record-delete",
    ),
    path(
        "registries/<int:type_pk>/import/",
        views.RegistryImportView.as_view(),
        name="platform-registry-import",
    ),
    # M05,M24-M30
    path("documents/", views.DocumentsListView.as_view(), name="platform-documents"),
    path("documents/new/", views.DocumentWizardCreateView.as_view(), name="platform-document-create"),
    path("documents/upload/", views.DocumentWizardCreateView.as_view(), name="platform-document-upload"),
    path("documents/<int:pk>/modal/", views.DocumentModalView.as_view(), name="platform-document-modal"),
    path(
        "documents/<int:pk>/version/",
        views.DocumentVersionUploadView.as_view(),
        name="platform-document-version",
    ),
    path("documents/<int:pk>/sign/", views.DocumentSignView.as_view(), name="platform-document-sign"),
    path("documents/<int:pk>/delete/", views.DocumentDeleteView.as_view(), name="platform-document-delete"),
    path("correspondence/inbox/", views.InboxListView.as_view(), name="platform-inbox"),
    path("correspondence/outbox/", views.OutboxListView.as_view(), name="platform-outbox"),
    path("correspondence/inbound/new/", views.InboundRegisterView.as_view(), name="platform-correspondence-inbound"),
    path(
        "correspondence/inbound/classify-preview/",
        views.InboundClassifyPreviewView.as_view(),
        name="platform-inbound-classify-preview",
    ),
    path("correspondence/outbound/new/", views.OutboundRegisterView.as_view(), name="platform-correspondence-outbound"),
    path(
        "correspondence/new/",
        views.InboundRegisterView.as_view(),
        name="platform-correspondence-create",
    ),
    path("correspondence/journal/", views.JournalListView.as_view(), name="platform-journal"),
    path(
        "correspondence/<int:pk>/",
        views.CorrespondenceDetailView.as_view(),
        name="platform-correspondence-detail",
    ),
    path(
        "correspondence/<int:pk>/modal/",
        views.CorrespondenceModalView.as_view(),
        name="platform-correspondence-modal",
    ),
    path(
        "correspondence/<int:pk>/panel/",
        views.CorrespondenceEmailPanelView.as_view(),
        name="platform-correspondence-panel",
    ),
    path(
        "correspondence/actions/",
        views.CorrespondenceMailActionsView.as_view(),
        name="platform-correspondence-actions",
    ),
    path(
        "correspondence/<int:pk>/route/",
        views.CorrespondenceRouteView.as_view(),
        name="platform-correspondence-route",
    ),
    path(
        "correspondence/<int:pk>/complete/",
        views.CorrespondenceCompleteView.as_view(),
        name="platform-correspondence-complete",
    ),
    path(
        "correspondence/<int:pk>/history/",
        views.CorrespondenceHistoryView.as_view(),
        name="platform-correspondence-history",
    ),
    path(
        "correspondence/print-templates/",
        views.PrintTemplateListView.as_view(),
        name="platform-print-templates",
    ),
    path(
        "correspondence/print-templates/new/",
        views.PrintTemplateCreateView.as_view(),
        name="platform-print-template-create",
    ),
    path(
        "correspondence/print-templates/<int:pk>/preview/",
        views.PrintTemplatePreviewView.as_view(),
        name="platform-print-template-preview",
    ),
    path("correspondence/signatures/", views.SignatureCenterView.as_view(), name="platform-signatures"),
    path(
        "correspondence/signatures/requests/<int:pk>/complete/",
        views.SignatureRequestCompleteView.as_view(),
        name="platform-signature-complete",
    ),
    path("correspondence/goskey/", views.GoskeyStubView.as_view(), name="platform-goskey"),
    path("correspondence/scan-batch/", views.ScanBatchView.as_view(), name="platform-scan-batch"),
    # M33-M36
    path("bpm/", views.BPMInstancesListView.as_view(), name="platform-bpm"),
    path("bpm/templates/", views.BPMTemplatesListView.as_view(), name="platform-bpm-templates"),
    path("bpm/templates/new/", views.BPMTemplateWizardView.as_view(), name="platform-bpm-template-create"),
    path(
        "bpm/templates/<int:pk>/modal/",
        views.BPMTemplateModalView.as_view(),
        name="platform-bpm-template-modal",
    ),
    path(
        "bpm/templates/<int:pk>/edit/",
        views.BPMTemplateUpdateView.as_view(),
        name="platform-bpm-template-edit",
    ),
    path("bpm/instances/", views.BPMInstancesListView.as_view(), name="platform-bpm-instances"),
    path("bpm/instances/<int:pk>/", views.BPMInstanceDetailView.as_view(), name="platform-bpm-instance"),
    path("bpm/start/", views.BPMStartView.as_view(), name="platform-bpm-start"),
    path("bpm/approvals/", views.BPMApprovalsListView.as_view(), name="platform-bpm-approvals"),
    path("bpm/task/<int:pk>/", views.BPMTaskDecisionView.as_view(), name="platform-bpm-task"),
    path("bpm/sla/", views.SLARulesListView.as_view(), name="platform-bpm-sla"),
    path("bpm/sla/new/", views.SLARuleWizardView.as_view(), name="platform-bpm-sla-create"),
    path("bpm/sla/monitor/", views.SLAMonitorView.as_view(), name="platform-bpm-sla-monitor"),
    path("bpm/regulations/", views.RegulationsListView.as_view(), name="platform-bpm-regulations"),
    path(
        "bpm/regulations/new/",
        views.RegulationWizardView.as_view(),
        name="platform-bpm-regulation-create",
    ),
    path(
        "bpm/regulations/<int:pk>/apply/",
        views.RegulationApplyView.as_view(),
        name="platform-bpm-regulation-apply",
    ),
    # M37–M41
    path("chat/", views.ChatListView.as_view(), name="platform-chat"),
    path("chat/new/", views.ChatCreateView.as_view(), name="platform-chat-create"),
    path("chat/<int:pk>/", views.ChatDetailView.as_view(), name="platform-chat-room"),
    path("chat/<int:pk>/send/", views.ChatPostView.as_view(), name="platform-chat-send"),
    path("chat/<int:pk>/delete/", views.ChatDeleteView.as_view(), name="platform-chat-delete"),
    path("comms/comments/", views.CommentsHubView.as_view(), name="platform-comments"),
    path("comms/mentions/", views.MentionsListView.as_view(), name="platform-mentions"),
    path("comms/mentions/<int:pk>/read/", views.MentionReadView.as_view(), name="platform-mention-read"),
    path("comms/subscriptions/", views.SubscriptionsListView.as_view(), name="platform-subscriptions"),
    path(
        "comms/subscriptions/<int:pk>/delete/",
        views.SubscriptionDeleteView.as_view(),
        name="platform-subscription-delete",
    ),
    path("comms/meetings/", views.MeetingsListView.as_view(), name="platform-meetings"),
    path("comms/meetings/new/", views.MeetingCreateView.as_view(), name="platform-meeting-create"),
    path("comms/messengers/", views.MessengersListView.as_view(), name="platform-messengers"),
    path("comms/messengers/new/", views.MessengerCreateView.as_view(), name="platform-messenger-create"),
    # M15-M21
    path("analytics/dashboard/", views.DashboardView.as_view(), name="platform-dashboard"),
    path("analytics/reports/", views.ReportsListView.as_view(), name="platform-reports"),
    path("analytics/reports/new/", views.ReportTemplateWizardView.as_view(), name="platform-report-create"),
    path(
        "analytics/reports/<int:pk>/modal/",
        views.ReportTemplateModalView.as_view(),
        name="platform-report-modal",
    ),
    path("analytics/regulatory/", views.RegulatoryReportsView.as_view(), name="platform-regulatory"),
    path("analytics/charts/", views.ChartsView.as_view(), name="platform-charts"),
    path("analytics/quality/", views.QualityView.as_view(), name="platform-quality"),
    path("analytics/overdue/", views.OverdueMonitorView.as_view(), name="platform-overdue"),
    path("analytics/departments/", views.DepartmentAnalyticsView.as_view(), name="platform-departments"),
    # M47–M66
    path("ai/", views.AiHubView.as_view(), name="platform-ai-hub"),
    path("ai/assistant/", views.AiAssistantView.as_view(), name="platform-ai-assistant"),
    path("ai/search/", views.AiSearchView.as_view(), name="platform-ai-search"),
    path("ai/tools/", views.AiToolsView.as_view(), name="platform-ai-tools"),
    path("ai/ocr/", views.AiOcrStubView.as_view(), name="platform-ai-ocr"),
    path("ai/policies/", views.AiPoliciesView.as_view(), name="platform-ai-policies"),
    path("ai/feedback/", views.AiFeedbackCreateView.as_view(), name="platform-ai-feedback"),
    path("ai/hitl/", views.AiHitlListView.as_view(), name="platform-ai-hitl"),
    path("ai/hitl/<int:pk>/review/", views.AiHitlReviewView.as_view(), name="platform-ai-hitl-review"),
    path("ai/hitl/create/", views.AiHitlCreateView.as_view(), name="platform-ai-hitl-create"),
    path("ai/knowledge/", views.KnowledgeListView.as_view(), name="platform-knowledge"),
    path("ai/knowledge/new/", views.KnowledgeCreateView.as_view(), name="platform-knowledge-create"),
    # M42–M45
    path("integrations/", views.IntegrationHubView.as_view(), name="platform-integrations"),
    path("integrations/endpoints/", views.IntegrationEndpointsView.as_view(), name="platform-integration-endpoints"),
    path(
        "integrations/endpoints/new/",
        views.IntegrationEndpointCreateView.as_view(),
        name="platform-integration-endpoint-create",
    ),
    path("integrations/messages/", views.IntegrationMessagesView.as_view(), name="platform-integrations-messages"),
    path(
        "integrations/messages/<int:pk>/dead-letter/",
        views.IntegrationDeadLetterView.as_view(),
        name="platform-integration-dead-letter",
    ),
    path(
        "integrations/messages/<int:pk>/modal/",
        views.IntegrationMessageModalView.as_view(),
        name="platform-integration-message-modal",
    ),
    path("integrations/<int:pk>/send/", views.IntegrationSendView.as_view(), name="platform-integration-send"),
    path(
        "integrations/messages/<int:pk>/retry/",
        views.IntegrationRetryView.as_view(),
        name="platform-integration-retry",
    ),
    path("integrations/api/", views.ApiDocsView.as_view(), name="platform-api-docs"),
    path("integrations/api/keys/new/", views.ApiKeyCreateView.as_view(), name="platform-api-key-create"),
    path("integrations/api/openapi.json", views.ApiOpenApiJsonView.as_view(), name="platform-api-openapi"),
    path("integrations/smev/", views.SmevHubView.as_view(), name="platform-smev"),
    path("integrations/smev/<int:pk>/receive/", views.SmevReceiveView.as_view(), name="platform-smev-receive"),
    path("integrations/external/", views.ExternalConnectorsView.as_view(), name="platform-external"),
    # M67–M72
    path("infra/", views.InfraHubView.as_view(), name="platform-infra"),
    path("infra/gis/", views.GisMapView.as_view(), name="platform-gis"),
    path("infra/gis/layers/new/", views.GeoLayerCreateView.as_view(), name="platform-geo-layer-create"),
    path("infra/gis/objects/new/", views.GeoObjectCreateView.as_view(), name="platform-geo-object-create"),
    path("infra/pwa/", views.PwaHubView.as_view(), name="platform-pwa"),
    path("infra/pwa/drafts/<int:pk>/sync/", views.PwaDraftSyncView.as_view(), name="platform-pwa-sync"),
    path("infra/sso/", views.SsoProvidersView.as_view(), name="platform-sso"),
    path("infra/sso/new/", views.SsoProviderCreateView.as_view(), name="platform-sso-create"),
    path("infra/etl/", views.EtlHubView.as_view(), name="platform-etl"),
    path("infra/etl/new/", views.EtlJobCreateView.as_view(), name="platform-etl-create"),
    path("infra/etl/<int:pk>/run/", views.EtlRunStartView.as_view(), name="platform-etl-run"),
    path("infra/etl/runs/<int:pk>/modal/", views.EtlRunModalView.as_view(), name="platform-etl-run-modal"),
    path("infra/data-hub/", views.DataHubView.as_view(), name="platform-data-hub"),
    path("infra/data-hub/new/", views.DataDatasetCreateView.as_view(), name="platform-data-hub-create"),
    path("infra/citizen/", views.CitizenPortalView.as_view(), name="platform-citizen"),
    path("infra/citizen/new/", views.CitizenAppealCreateView.as_view(), name="platform-citizen-create"),
    path(
        "infra/citizen/<int:pk>/modal/",
        views.CitizenAppealModalView.as_view(),
        name="platform-citizen-modal",
    ),
    # M73–M77
    path("ops/", views.OpsHubView.as_view(), name="platform-ops"),
    path("ops/nsi/", views.NsiListView.as_view(), name="platform-nsi"),
    path("ops/case-kinds/", views.CaseKindsListView.as_view(), name="platform-case-kinds"),
    path("ops/nsi/new/", views.NsiClassifierCreateView.as_view(), name="platform-nsi-create"),
    path("ops/nsi/<int:pk>/", views.NsiClassifierDetailView.as_view(), name="platform-nsi-detail"),
    path(
        "ops/nsi/<int:pk>/values/new/",
        views.NsiValueCreateView.as_view(),
        name="platform-nsi-value-create",
    ),
    path("ops/forms/", views.FormSchemasListView.as_view(), name="platform-form-schemas"),
    path("ops/forms/new/", views.FormSchemaCreateView.as_view(), name="platform-form-schema-create"),
    path(
        "ops/forms/<int:pk>/edit/",
        views.FormSchemaEditView.as_view(),
        name="platform-form-schema-edit",
    ),
    path("ops/bulk/", views.BulkOperationsView.as_view(), name="platform-bulk-ops"),
    path("ops/exports/", views.ExportsListView.as_view(), name="platform-exports"),
    path("ops/directives/", views.DirectivesListView.as_view(), name="platform-directives"),
    path(
        "ops/directives/new/",
        views.DirectiveCreateView.as_view(),
        name="platform-directive-create",
    ),
    path(
        "ops/directives/<int:pk>/report/",
        views.DirectiveReportView.as_view(),
        name="platform-directive-report",
    ),
    path(
        "ops/directives/<int:pk>/modal/",
        views.DirectiveModalView.as_view(),
        name="platform-directive-modal",
    ),
    # M78–M82
    path("exploit/", views.ExploitHubView.as_view(), name="platform-exploit"),
    path(
        "exploit/notifications/",
        views.NotificationTemplatesView.as_view(),
        name="platform-notification-templates",
    ),
    path(
        "exploit/notifications/new/",
        views.NotificationTemplateCreateView.as_view(),
        name="platform-notification-template-create",
    ),
    path("exploit/antivirus/", views.AntivirusView.as_view(), name="platform-antivirus"),
    path("exploit/pii/", views.PiiMaskingView.as_view(), name="platform-pii"),
    path("exploit/backups/", views.BackupsView.as_view(), name="platform-backups"),
    path("exploit/health/", views.HealthView.as_view(), name="platform-health"),
    path("exploit/mail/", views.MailSettingsView.as_view(), name="platform-mail-settings"),
    path("exploit/mail/test/", views.MailTestSendView.as_view(), name="platform-mail-test"),
    path("exploit/mail/sync/", views.MailSyncInboundView.as_view(), name="platform-mail-sync"),
    path("exploit/mail/delivery/", views.MailDeliveryLogView.as_view(), name="platform-mail-delivery"),
    path("exploit/product-passport/", views.ProductPassportView.as_view(), name="platform-product-passport"),
    path(
        "exploit/product-passport/export/",
        views.ProductPassportExportView.as_view(),
        name="platform-product-passport-export",
    ),
    # M83–M86
    path("ux/", views.UxHubView.as_view(), name="platform-ux"),
    path("ux/licenses/", views.LicensesView.as_view(), name="platform-licenses"),
    path("ux/onboarding/", views.OnboardingListView.as_view(), name="platform-onboarding"),
    path("ux/onboarding/new/", views.OnboardingCreateView.as_view(), name="platform-onboarding-create"),
    path("ux/dashboards/", views.DashboardLayoutsView.as_view(), name="platform-dashboard-layouts"),
    path(
        "ux/dashboards/new/",
        views.DashboardLayoutCreateView.as_view(),
        name="platform-dashboard-layout-create",
    ),
    path("ux/marketplace/", views.MarketplaceView.as_view(), name="platform-marketplace"),
    path(
        "ux/marketplace/<int:pk>/install/",
        views.MarketplaceInstallView.as_view(),
        name="platform-marketplace-install",
    ),
    # M46,M06,M12,M14
    path("archive/audio/", views.AudioArchiveListView.as_view(), name="platform-audio"),
    path("archive/audio/upload/", views.AudioUploadView.as_view(), name="platform-audio-upload"),
    path("archive/audio/<int:pk>/", views.AudioDetailView.as_view(), name="platform-audio-detail"),
    path("archive/audio/<int:pk>/modal/", views.AudioModalView.as_view(), name="platform-audio-modal"),
    path(
        "archive/audio/<int:pk>/transcribe/",
        views.AudioTranscribeView.as_view(),
        name="platform-audio-transcribe",
    ),
    path("archive/cases/", views.ArchiveCasesListView.as_view(), name="platform-archive-cases"),
    path(
        "archive/cases/<int:pk>/modal/",
        views.ArchiveCaseModalView.as_view(),
        name="platform-archive-case-modal",
    ),
    path(
        "archive/cases/<int:pk>/legal-hold/",
        views.ArchiveCaseLegalHoldView.as_view(),
        name="platform-archive-case-legal-hold",
    ),
    path(
        "archive/cases/<int:pk>/restore/",
        views.ArchiveCaseRestoreView.as_view(),
        name="platform-archive-case-restore",
    ),
    path(
        "archive/cases/<int:pk>/export/",
        views.ArchiveCaseExportView.as_view(),
        name="platform-archive-case-export",
    ),
    path(
        "archive/cases/purge-expired/",
        views.ArchivePurgeExpiredView.as_view(),
        name="platform-archive-purge",
    ),
    path("notifications/", views.NotificationsView.as_view(), name="platform-notifications"),
    path(
        "notifications/<int:pk>/read/",
        views.NotificationReadView.as_view(),
        name="platform-notification-read",
    ),
    path(
        "notifications/read-all/",
        views.NotificationReadAllView.as_view(),
        name="platform-notifications-read-all",
    ),
    path("activity/", views.ActivityView.as_view(), name="platform-activity"),
    # M43 REST
    path("api/v1/health/", api_views.api_health, name="api-v1-health"),
    path("api/v1/cases/", api_views.api_cases, name="api-v1-cases"),
    path("api/v1/tasks/", api_views.api_tasks, name="api-v1-tasks"),
    path("api/v1/modules/", api_views.api_modules, name="api-v1-modules"),
    path("api/v1/search/", api_views.api_search, name="api-v1-search"),
    path("api/v1/openapi.json", api_views.api_openapi_contract, name="api-v1-openapi"),
    path("api/v1/calendar/events/", api_views.api_calendar_events, name="api-v1-calendar-events"),
    path("api/v1/integration/messages/", api_views.api_integration_messages, name="api-v1-integration-messages"),
    path(
        "api/v1/integration/messages/<int:pk>/retry/",
        api_views.api_integration_message_retry,
        name="api-v1-integration-retry",
    ),
    path(
        "api/v1/integration/messages/<int:pk>/dead-letter/",
        api_views.api_integration_message_dead_letter,
        name="api-v1-integration-dead-letter",
    ),
    path(
        "api/v1/integration/queue/process/",
        api_views.api_integration_queue_process,
        name="api-v1-integration-queue-process",
    ),
    path(
        "api/v1/notifications/delivery/",
        api_views.api_notification_delivery,
        name="api-v1-notification-delivery",
    ),
    path("api/v1/ai/policy/", api_views.api_ai_policy, name="api-v1-ai-policy"),
    path("api/v1/dadata/status/", views_dadata.dadata_status, name="api-v1-dadata-status"),
    path("api/v1/dadata/suggest/", views_dadata.dadata_suggest, name="api-v1-dadata-suggest"),
    path(
        "api/v1/integration/inbound/<slug:subsystem_code>/<slug:endpoint_code>/",
        api_views_integration.api_integration_inbound,
        name="api-v1-integration-inbound",
    ),
    path(
        "api/v1/telegram/<slug:subsystem_code>/",
        api_views_integration.api_telegram_webhook,
        name="api-v1-telegram-webhook",
    ),
    path(
        "public/<slug:subsystem_code>/appeal/",
        views_public.UzhvPublicAppealView.as_view(),
        name="uzhv-public-appeal",
    ),
    path("platform/search/", views.GlobalSearchView.as_view(), name="platform-global-search"),
    path("platform/privacy-mode/", views.PrivacyModeToggleView.as_view(), name="platform-privacy-mode"),
    path("platform/onboarding/", views.OnboardingChecklistView.as_view(), name="platform-onboarding-checklist"),
    # Studio — визуальные конструкторы
    path("studio/", views.StudioHubView.as_view(), name="platform-studio"),
    path("studio/forms/", views.StudioFormBuilderView.as_view(), name="platform-studio-forms"),
    path("studio/forms/<int:pk>/", views.StudioFormBuilderView.as_view(), name="platform-studio-form-edit"),
    path("studio/bpm/", views.StudioBpmEditorView.as_view(), name="platform-studio-bpm"),
    path("studio/bpm/<int:pk>/", views.StudioBpmEditorView.as_view(), name="platform-studio-bpm-edit"),
    path("studio/menu/", views.StudioMenuEditorView.as_view(), name="platform-studio-menu"),
    path("studio/dashboard/", views.StudioDashboardEditorView.as_view(), name="platform-studio-dashboard"),
    path("studio/correspondence/", views.StudioCorrespondenceEditorView.as_view(), name="platform-studio-correspondence"),
    path("studio/print/", views.StudioPrintEditorView.as_view(), name="platform-studio-print"),
    path("studio/print/<int:pk>/", views.StudioPrintEditorView.as_view(), name="platform-studio-print-edit"),
    path("studio/permissions/", views.StudioPermissionsEditorView.as_view(), name="platform-studio-permissions"),
    path("studio/nsi/", views.StudioNsiEditorView.as_view(), name="platform-studio-nsi"),
    path("studio/nsi/<int:pk>/", views.StudioNsiEditorView.as_view(), name="platform-studio-nsi-edit"),
    path("studio/integration/", views.StudioIntegrationEditorView.as_view(), name="platform-studio-integration"),
    path("studio/integration/<int:pk>/", views.StudioIntegrationEditorView.as_view(), name="platform-studio-integration-edit"),
    path("studio/cabinet/", views.StudioCabinetEditorView.as_view(), name="platform-studio-cabinet"),
    path("studio/api/<slug:editor>/save/", views.StudioSaveApiView.as_view(), name="platform-studio-save"),
    # АИС УЖВ
    path("uzhv/bulk/", views.UzhvBulkActionView.as_view(), name="uzhv-bulk"),
    path("uzhv/deadlines/", views.UzhvDeadlinesCalendarView.as_view(), name="uzhv-deadlines"),
    path("uzhv/deadlines/export.csv", views.UzhvDeadlinesExportView.as_view(), name="uzhv-deadlines-export"),
    path("uzhv/overdue/export.csv", views.UzhvOverdueExportView.as_view(), name="uzhv-overdue-export"),
    path("uzhv/api/alerts/", views.UzhvMobileAlertsView.as_view(), name="uzhv-mobile-alerts"),
    path("uzhv/api/push/subscribe/", views.UzhvPushSubscribeView.as_view(), name="uzhv-push-subscribe"),
    path("uzhv/api/push/test/", views.UzhvPushTestView.as_view(), name="uzhv-push-test"),
    path("uzhv/sw.js", views.UzhvServiceWorkerView.as_view(), name="uzhv-service-worker"),
    path("uzhv/workload/export.xlsx", views.UzhvWorkloadExportView.as_view(), name="uzhv-workload-export-xlsx"),
    path("uzhv/assignee/<int:user_id>/", views.UzhvAssigneeDashboardView.as_view(), name="uzhv-assignee"),
    path("uzhv/create/", views_uzhv_wizard.UzhvCreateHubView.as_view(), name="uzhv-create-hub"),
    path(
        "uzhv/create/chain/",
        views_uzhv_wizard.UzhvChainWizardCreateView.as_view(),
        name="uzhv-create-chain",
    ),
    path("uzhv/", views.UzhvHubView.as_view(), name="uzhv-hub"),
    path("uzhv/cases/", views.UzhvCasesListView.as_view(), name="uzhv-cases"),
    path("uzhv/cases/recalc-queue/", views.UzhvQueueRecalcView.as_view(), name="uzhv-queue-recalc"),
    path("uzhv/citizens/", views.UzhvCitizensListView.as_view(), name="uzhv-citizens"),
    path("uzhv/fund/", views.UzhvFundListView.as_view(), name="uzhv-fund"),
    path("uzhv/fund/map/", views.UzhvFundMapView.as_view(), name="uzhv-fund-map"),
    path("uzhv/fund/new/", views.UzhvBuildingCreateView.as_view(), name="uzhv-building-create"),
    path("uzhv/fund/<int:pk>/modal/", views.UzhvBuildingModalView.as_view(), name="uzhv-building-modal"),
    path("uzhv/fund/<int:pk>/edit/", views.UzhvBuildingUpdateView.as_view(), name="uzhv-building-edit"),
    path("uzhv/fund/<int:pk>/", views.UzhvBuildingDetailView.as_view(), name="uzhv-building-detail"),
    path("uzhv/fund/premises/<int:pk>/edit/", views.UzhvPremiseUpdateView.as_view(), name="uzhv-premise-edit"),
    path("uzhv/resettlement/", views.UzhvResettlementListView.as_view(), name="uzhv-resettlement"),
    path("uzhv/unfit-premises/", views.UzhvUnfitPremisesListView.as_view(), name="uzhv-unfit-premises"),
    path("uzhv/fund/accounts/", views.UzhvPersonalAccountsListView.as_view(), name="uzhv-personal-accounts"),
    path(
        "uzhv/fund/premises/<int:premise_pk>/account/",
        views.UzhvPersonalAccountEditView.as_view(),
        name="uzhv-personal-account-edit",
    ),
    path(
        "uzhv/fund/accounts/<int:pk>/extract.docx",
        views.UzhvPersonalAccountExtractView.as_view(),
        name="uzhv-personal-account-extract",
    ),
    path("uzhv/private-premises/", views.UzhvPrivatePremisesListView.as_view(), name="uzhv-private-premises"),
    path("uzhv/private-premises/new/", views.UzhvPrivatePremiseCreateView.as_view(), name="uzhv-private-premise-create"),
    path("uzhv/private-premises/<int:pk>/edit/", views.UzhvPrivatePremiseUpdateView.as_view(), name="uzhv-private-premise-edit"),
    path("uzhv/inspections/", views.UzhvInspectionsListView.as_view(), name="uzhv-inspections"),
    path("uzhv/inspection-plans/", views.UzhvInspectionPlansListView.as_view(), name="uzhv-inspection-plans"),
    path("uzhv/inspection-plans/new/", views.UzhvInspectionPlanCreateView.as_view(), name="uzhv-inspection-plan-create"),
    path("uzhv/inspection-plans/<int:pk>/", views.UzhvInspectionPlanDetailView.as_view(), name="uzhv-inspection-plan-detail"),
    path("uzhv/inspection-plans/<int:pk>/edit/", views.UzhvInspectionPlanUpdateView.as_view(), name="uzhv-inspection-plan-edit"),
    path("uzhv/inspection-orders/", views.UzhvInspectionOrdersListView.as_view(), name="uzhv-inspection-orders"),
    path("uzhv/inspection-orders/new/", views.UzhvInspectionOrderCreateView.as_view(), name="uzhv-inspection-order-create"),
    path("uzhv/inspection-orders/<int:pk>/edit/", views.UzhvInspectionOrderUpdateView.as_view(), name="uzhv-inspection-order-edit"),
    path("uzhv/reconstruction/", views.UzhvReconstructionListView.as_view(), name="uzhv-reconstruction"),
    path("uzhv/enforcement/", views.UzhvEnforcementProceedingsListView.as_view(), name="uzhv-enforcement"),
    path("uzhv/enforcement/new/", views.UzhvEnforcementProceedingCreateView.as_view(), name="uzhv-enforcement-create"),
    path("uzhv/enforcement/<int:pk>/edit/", views.UzhvEnforcementProceedingUpdateView.as_view(), name="uzhv-enforcement-edit"),
    path("uzhv/inspections/new/", views.UzhvInspectionCreateView.as_view(), name="uzhv-inspection-create"),
    path("uzhv/inspections/<int:pk>/modal/", views.UzhvInspectionModalView.as_view(), name="uzhv-inspection-modal"),
    path("uzhv/inspections/<int:pk>/edit/", views.UzhvInspectionUpdateView.as_view(), name="uzhv-inspection-edit"),
    path("uzhv/prescriptions/", views.UzhvPrescriptionsListView.as_view(), name="uzhv-prescriptions"),
    path("uzhv/prescriptions/<int:pk>/modal/", views.UzhvPrescriptionModalView.as_view(), name="uzhv-prescription-modal"),
    path("uzhv/prescriptions/<int:pk>/edit/", views.UzhvPrescriptionUpdateView.as_view(), name="uzhv-prescription-edit"),
    path("uzhv/court-cases/", views.UzhvCourtCasesListView.as_view(), name="uzhv-court-cases"),
    path("uzhv/court-cases/new/", views.UzhvCourtCaseCreateView.as_view(), name="uzhv-court-case-create"),
    path("uzhv/court-cases/<int:pk>/modal/", views.UzhvCourtCaseModalView.as_view(), name="uzhv-court-case-modal"),
    path("uzhv/court-cases/<int:pk>/edit/", views.UzhvCourtCaseUpdateView.as_view(), name="uzhv-court-case-edit"),
    path("uzhv/contracts/", views.UzhvContractsListView.as_view(), name="uzhv-contracts"),
    path("uzhv/contracts/new/", views.UzhvContractCreateView.as_view(), name="uzhv-contract-create"),
    path("uzhv/contracts/<int:pk>/edit/", views.UzhvContractUpdateView.as_view(), name="uzhv-contract-edit"),
    path("uzhv/contracts/<int:pk>/consents/", views.UzhvContractConsentsView.as_view(), name="uzhv-contract-consents"),
    path(
        "uzhv/contracts/<int:pk>/consents/<int:consent_pk>/document.docx",
        views.UzhvContractConsentDocumentView.as_view(),
        name="uzhv-contract-consent-document",
    ),
    path("uzhv/contracts/<int:pk>/modal/", views.UzhvContractModalView.as_view(), name="uzhv-contract-modal"),
    path("uzhv/appeals/", views.UzhvAppealsListView.as_view(), name="uzhv-appeals"),
    path(
        "uzhv/appeals/new/",
        views_uzhv_wizard.UzhvAppealWizardCreateView.as_view(),
        name="uzhv-appeal-create",
    ),
    path("uzhv/appeals/<int:pk>/modal/", views.UzhvAppealModalView.as_view(), name="uzhv-appeal-modal"),
    path("uzhv/appeals/<int:pk>/edit/", views.UzhvAppealUpdateView.as_view(), name="uzhv-appeal-edit"),
    path(
        "uzhv/appeals/<int:pk>/response.docx",
        views.UzhvAppealDocumentView.as_view(),
        name="uzhv-appeal-response-docx",
    ),
    path("uzhv/cases/new/", views.UzhvCaseCreateView.as_view(), name="uzhv-case-create"),
    path("uzhv/cases/<int:pk>/modal/", views.UzhvCaseModalView.as_view(), name="uzhv-case-modal"),
    path("uzhv/cases/<int:pk>/edit/", views.UzhvCaseUpdateView.as_view(), name="uzhv-case-edit"),
    path(
        "uzhv/citizens/new/",
        views_uzhv_wizard.UzhvCitizenWizardCreateView.as_view(),
        name="uzhv-citizen-create",
    ),
    path("uzhv/citizens/<int:pk>/modal/", views.UzhvCitizenModalView.as_view(), name="uzhv-citizen-modal"),
    path("uzhv/citizens/<int:pk>/edit/", views.UzhvCitizenUpdateView.as_view(), name="uzhv-citizen-edit"),
    path("uzhv/qr/<slug:entity>/<int:pk>.svg", views_qr.uzhv_qr, name="uzhv-qr"),
    path("uzhv/qr/citizens/<int:pk>.svg", views_qr.uzhv_qr_citizen, name="uzhv-qr-citizen"),
    path("uzhv/qr/appeals/<int:pk>.svg", views_qr.uzhv_qr_appeal, name="uzhv-qr-appeal"),
    path("uzhv/qr/cases/<int:pk>.svg", views_qr.uzhv_qr_case, name="uzhv-qr-case"),
    path(
        "uzhv/qr/public/<slug:subsystem_code>.svg",
        views_qr.uzhv_qr_public_appeal,
        name="uzhv-qr-public",
    ),
    path("uzhv/cases/<int:pk>/low-income/", views.UzhvLowIncomeView.as_view(), name="uzhv-case-low-income"),
    path(
        "uzhv/cases/<int:pk>/document/<slug:code>/",
        views.UzhvCaseDocumentView.as_view(),
        name="uzhv-case-document",
    ),
    path("uzhv/cases/<int:pk>/package.zip", views.UzhvCaseZipView.as_view(), name="uzhv-case-zip"),
    path("uzhv/reports/", views.UzhvReportsHubView.as_view(), name="uzhv-reports"),
    path("uzhv/reports/<slug:code>/export.csv", views.UzhvReportExportView.as_view(), {"fmt": "csv"}, name="uzhv-report-export"),
    path("uzhv/reports/<slug:code>/export.xlsx", views.UzhvReportExportView.as_view(), {"fmt": "xlsx"}, name="uzhv-report-export-xlsx"),
    path("uzhv/reports/<slug:code>/export.pdf", views.UzhvReportExportView.as_view(), {"fmt": "pdf"}, name="uzhv-report-export-pdf"),
    path("uzhv/interagency/", views.UzhvInteragencyListView.as_view(), name="uzhv-interagency"),
    path("uzhv/interagency/new/", views.UzhvInteragencyCreateView.as_view(), name="uzhv-interagency-create"),
    path("uzhv/interagency/<int:pk>/modal/", views.UzhvInteragencyModalView.as_view(), name="uzhv-interagency-modal"),
    path("uzhv/interagency/<int:pk>/edit/", views.UzhvInteragencyUpdateView.as_view(), name="uzhv-interagency-edit"),
    path("uzhv/admin-protocols/", views.UzhvAdminProtocolsListView.as_view(), name="uzhv-admin-protocols"),
    path("uzhv/admin-protocols/<int:pk>/modal/", views.UzhvAdminProtocolModalView.as_view(), name="uzhv-admin-protocol-modal"),
    path("uzhv/admin-protocols/<int:pk>/edit/", views.UzhvAdminProtocolUpdateView.as_view(), name="uzhv-admin-protocol-edit"),
    path("uzhv/young-families/", views.UzhvYoungFamiliesListView.as_view(), name="uzhv-young-families"),
    path("uzhv/young-families/<int:pk>/modal/", views.UzhvYoungFamilyModalView.as_view(), name="uzhv-young-family-modal"),
    path("uzhv/young-families/<int:pk>/edit/", views.UzhvYoungFamilyEditView.as_view(), name="uzhv-young-family-edit"),
    path("uzhv/orphans/", views.UzhvOrphansListView.as_view(), name="uzhv-orphans"),
    path("uzhv/orphans/<int:pk>/modal/", views.UzhvOrphanModalView.as_view(), name="uzhv-orphan-modal"),
    path("uzhv/orphans/<int:pk>/edit/", views.UzhvOrphanEditView.as_view(), name="uzhv-orphan-edit"),
    path("uzhv/contracts/import/", views.UzhvContractImportView.as_view(), name="uzhv-contract-import"),
]
