"""Русификация и уменьшение демо-цифр на главной."""
from pathlib import Path

p = Path(__file__).resolve().parents[1] / "delayu" / "templates" / "platform" / "home.html"
t = p.read_text(encoding="utf-8")

repl = [
    ("+22%", "+5%"),
    ("155k", "24"),
    ("Last 4 Month", "За месяц"),
    ("$38.5k", "12"),
    ("+62%", "+8%"),
    ("Sessions", "Активность"),
    ("Report", "Сводка"),
    ("Last 4 Month", "За месяц"),
    ("Total Earning", "Итого"),
    ("Total Profit", "Прибыль"),
    ("New Project", "Новые дела"),
    ("$86.4k", "8,4 тыс."),
    ("$25.6k", "2,1 тыс."),
    ("Project Timeline", "Сроки дел"),
    ("Activity Timeline", "Лента событий"),
    ("View Profile", "Профиль"),
    ("Upgrade Account", "Расширить доступ"),
    ("Upgrade", "Подробнее"),
    ("Total Revenue", "Оборот"),
    ("Total Sales", "Дела"),
    ("Total Profit", "Выполнено"),
    ("Overview", "Обзор"),
    ("Analytics", "Аналитика"),
    ("Last Week", "Прошлая нед."),
    ("This Week", "Текущая нед."),
    ("Performance", "Показатели"),
    ("Revenue", "Оборот"),
    ("Expenses", "Расходы"),
    ("Profit", "Результат"),
    ("Earning Reports", "Отчёт"),
    ("Weekly Earnings Overview", "Недельная сводка"),
    ("Support Tracker", "Поддержка"),
    ("Last 7 Days", "7 дней"),
    ("Total Tickets", "Обращения"),
    ("New Tickets", "Новые"),
    ("Open Tickets", "Открытые"),
    ("Response Time", "Время ответа"),
    ("Sales Overview", "Сводка по делам"),
    ("Vinnie Mostowy", "Иванов А."),
    ("Allen Rieske", "Петров Б."),
    ("Julee Rossignol", "Сидорова В."),
    ("title=\"3 more\"", "title=\"ещё 3\""),
    ("+3", "+3"),
    ("INVOICE", "СЧЁТ"),
    ("Paid", "Оплачен"),
    ("Unpaid", "Не оплачен"),
    ("Pending", "Ожидает"),
    ("Download", "Скачать"),
    ("View", "Открыть"),
    ("Delete", "Удалить"),
    ("Edit", "Изменить"),
    ("User", "Пользователь"),
    ("Admin", "Администратор"),
    ("Designer", "Аналитик"),
    ("Developer", "Разработчик"),
    ("12 Invoices have been paid", "12 счетов оплачено"),
    ("Client Meeting", "Совещание"),
    ("Create a new project for client", "Новое дело по запросу"),
    ("Team Meeting", "Совещание команды"),
    ("Bootstrap Project", "Пилотный проект"),
    ("Assigned Task", "Назначена задача"),
    ("Marketing Campaign", "Кампания"),
    ("Design Review", "Проверка макета"),
    ("minutes ago", "мин. назад"),
    ("hours ago", "ч. назад"),
    ("days ago", "дн. назад"),
    ("Yesterday", "Вчера"),
    ("Today", "Сегодня"),
    ("Order", "Заказ"),
    ("Transactions", "Операции"),
    ("Congratulations", "Поздравляем"),
    ("You have done 72% more sales today.", "Сегодня обработано на 12% больше дел."),
    ("Check your new badge in your profile.", "Проверьте профиль в личном кабинете."),
    ("Monthly Campaign State", "Состояние кампании"),
    ("8.52k Social Visitors", "8,5 тыс. посещений"),
    ("Sales by Countries", "По регионам"),
    ("Delivery Exceptions", "Исключения доставки"),
    ("Website Analytics", "Веб-аналитика"),
    ("Average Daily Traffic", "Средний трафик"),
    ("Referral", "Переходы"),
    ("Direct", "Прямые"),
    ("Organic", "Органика"),
    ("Campaign", "Кампания"),
    ("Finance", "Финансы"),
    ("Orders", "Заказы"),
    ("Customers", "Клиенты"),
    ("Products", "Продукты"),
    ("Categories", "Категории"),
    ("Stock", "Склад"),
    ("Reviews", "Отзывы"),
    ("Comments", "Комментарии"),
    ("Settings", "Настройки"),
    ("Help", "Справка"),
    ("Contact", "Контакты"),
    ("FAQ", "Вопросы"),
    ("Blog", "Блог"),
    ("News", "Новости"),
    ("Events", "События"),
    ("Calendar", "Календарь"),
    ("Tasks", "Задачи"),
    ("Projects", "Проекты"),
    ("Teams", "Команды"),
    ("Members", "Участники"),
    ("Roles", "Роли"),
    ("Permissions", "Права"),
    ("Logs", "Журнал"),
    ("Reports", "Отчёты"),
    ("Dashboard", "Панель"),
    ("Home", "Главная"),
    ("Profile", "Профиль"),
    ("Account", "Аккаунт"),
    ("Security", "Безопасность"),
    ("Notifications", "Уведомления"),
    ("Connections", "Связи"),
    ("Billing", "Работа"),
    ("Invoice", "Счёт"),
    ("Payment", "Оплата"),
    ("Subscription", "Подписка"),
    ("Plan", "Тариф"),
    ("Free", "Бесплатно"),
    ("Pro", "Про"),
    ("Enterprise", "Корпоративный"),
    ("Basic", "Базовый"),
    ("Standard", "Стандарт"),
    ("Premium", "Премиум"),
    ("Popular", "Популярный"),
    ("Recommended", "Рекомендуем"),
    ("Featured", "Избранное"),
    ("New", "Новое"),
    ("Hot", "Горячее"),
    ("Sale", "Скидка"),
    ("Off", "Выкл"),
    ("On", "Вкл"),
    ("Yes", "Да"),
    ("No", "Нет"),
    ("OK", "ОК"),
    ("Cancel", "Отмена"),
    ("Save", "Сохранить"),
    ("Submit", "Отправить"),
    ("Search", "Поиск"),
    ("Filter", "Фильтр"),
    ("Sort", "Сортировка"),
    ("Export", "Экспорт"),
    ("Import", "Импорт"),
    ("Print", "Печать"),
    ("Copy", "Копировать"),
    ("Paste", "Вставить"),
    ("Cut", "Вырезать"),
    ("Undo", "Отменить"),
    ("Redo", "Повторить"),
    ("Refresh", "Обновить"),
    ("Reload", "Перезагрузить"),
    ("Loading", "Загрузка"),
    ("Error", "Ошибка"),
    ("Success", "Успех"),
    ("Warning", "Предупреждение"),
    ("Info", "Информация"),
    ("Close", "Закрыть"),
    ("Open", "Открыть"),
    ("Show", "Показать"),
    ("Hide", "Скрыть"),
    ("More", "Ещё"),
    ("Less", "Меньше"),
    ("All", "Все"),
    ("None", "Нет"),
    ("Other", "Другое"),
    ("Unknown", "Неизвестно"),
    ("Default", "По умолчанию"),
    ("Custom", "Свой"),
    ("Auto", "Авто"),
    ("Manual", "Вручную"),
    ("Online", "В сети"),
    ("Offline", "Не в сети"),
    ("Active", "Активен"),
    ("Inactive", "Неактивен"),
    ("Enabled", "Включено"),
    ("Disabled", "Выключено"),
    ("Public", "Публичный"),
    ("Private", "Приватный"),
    ("Draft", "Черновик"),
    ("Published", "Опубликовано"),
    ("Archived", "В архиве"),
    ("Deleted", "Удалено"),
    ("Restored", "Восстановлено"),
    ("Created", "Создано"),
    ("Updated", "Обновлено"),
    ("Modified", "Изменено"),
    ("Added", "Добавлено"),
    ("Removed", "Удалено"),
    ("Moved", "Перемещено"),
    ("Renamed", "Переименовано"),
    ("Shared", "Общий"),
    ("Locked", "Заблокировано"),
    ("Unlocked", "Разблокировано"),
    ("Verified", "Проверено"),
    ("Unverified", "Не проверено"),
    ("Approved", "Одобрено"),
    ("Rejected", "Отклонено"),
    ("Pending", "Ожидает"),
    ("Completed", "Завершено"),
    ("In Progress", "В работе"),
    ("Failed", "Ошибка"),
    ("Cancelled", "Отменено"),
    ("Scheduled", "Запланировано"),
    ("Expired", "Истекло"),
    ("Valid", "Действует"),
    ("Invalid", "Недействителен"),
]

for a, b in repl:
    t = t.replace(a, b)

p.write_text(t, encoding="utf-8")
print("updated", p)
