# Generated by Django 5.2.14 on 2026-05-27 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('group', models.CharField(choices=[('core', 'Ядро'), ('workplace', 'Рабочее место'), ('analytics', 'Аналитика'), ('cases', 'Дела и реестры'), ('docs', 'Документооборот'), ('bpm', 'Бизнес-процессы'), ('comms', 'Коммуникации'), ('integration', 'Интеграции'), ('archive', 'Архив'), ('ai', 'ИИ'), ('infra', 'Инфраструктура'), ('nsi', 'НСИ и операции'), ('ops', 'Эксплуатация'), ('ux', 'UX и лицензии')], default='core', max_length=32, verbose_name='Группа')),
                ('is_core', models.BooleanField(default=False, verbose_name='Ядро')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='В каталоге')),
            ],
            options={
                'verbose_name': 'Модуль каталога',
                'verbose_name_plural': 'Каталог модулей',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действует'), ('archived', 'Архив')], default='draft', max_length=16, verbose_name='Статус')),
                ('primary_color', models.CharField(blank=True, default='#666cff', max_length=16, verbose_name='Цвет бренда')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подсистема',
                'verbose_name_plural': 'Подсистемы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Код')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
                'unique_together': {('subsystem', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='delayu.organization')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
                'unique_together': {('subsystem', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_change', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.modulecatalog')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='delayu.role')),
            ],
            options={
                'verbose_name': 'Право на модуль',
                'verbose_name_plural': 'Права на модули',
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='SubsystemMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='delayu.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='delayu.role')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='delayu.subsystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystem_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Членство в подсистеме',
                'verbose_name_plural': 'Членства в подсистемах',
                'unique_together': {('user', 'subsystem', 'organization', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SubsystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включён')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystem_links', to='delayu.modulecatalog')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Модуль подсистемы',
                'verbose_name_plural': 'Модули подсистемы',
                'unique_together': {('subsystem', 'module')},
            },
        ),
    ]
