# Generated by Django 5.2.14 on 2026-05-27 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BPMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Экземпляр процесса',
            },
        ),
        migrations.CreateModel(
            name='SystemHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=64)),
                ('target_repr', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='delayu.subsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=8)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='delayu.subsystem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subsystem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='delayu.subsystem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BPMTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=64)),
                ('step_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Согласовано'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delayu.bpminstance')),
            ],
            options={
                'verbose_name': 'Задача согласования',
            },
        ),
        migrations.CreateModel(
            name='BPMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('steps', models.JSONField(default=list)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpm_templates', to='delayu.subsystem')),
            ],
            options={
                'unique_together': {('subsystem', 'code')},
            },
        ),
        migrations.AddField(
            model_name='bpminstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delayu.bpmtemplate'),
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('waiting', 'Ожидание'), ('done', 'Исполнено'), ('archived', 'В архиве')], default='new', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('description', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.organization')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
                'ordering': ['-updated_at'],
                'unique_together': {('subsystem', 'number')},
            },
        ),
        migrations.AddField(
            model_name='bpminstance',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpm_instances', to='delayu.casefile'),
        ),
        migrations.CreateModel(
            name='AudioArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='audio/%Y/%m/')),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('transcript', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_items', to='delayu.subsystem')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_items', to='delayu.casefile')),
            ],
            options={
                'verbose_name': 'Аудиозапись',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delayu.casefile')),
                ('members', models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Чат',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='delayu.chatroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Входящее'), ('out', 'Исходящее')], max_length=8)),
                ('reg_number', models.CharField(db_index=True, max_length=64)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=500)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('registered', 'Зарегистрировано'), ('in_work', 'В работе'), ('sent', 'Отправлено'), ('closed', 'Закрыто')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='delayu.casefile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correspondence_created', to=settings.AUTH_USER_MODEL)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Корреспонденция',
                'ordering': ['-reg_date', '-reg_number'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.subsystem')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Делегирование',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='delayu.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='delayu.department')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='delayu.casefile')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='delayu.subsystem')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='delayu.casefile')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.subsystem')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='delayu.documentfile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result_file', models.FileField(blank=True, upload_to='exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.subsystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('url_path', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('endpoint_type', models.CharField(max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='delayu.subsystem')),
            ],
            options={
                'unique_together': {('subsystem', 'code')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=8)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='delayu.integrationendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Статья базы знаний',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.subsystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delayu_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NSIClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nsi_classifiers', to='delayu.subsystem')),
            ],
            options={
                'unique_together': {('subsystem', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('headcount', models.PositiveSmallIntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='delayu.department')),
            ],
            options={
                'verbose_name': 'Должность',
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('correspondence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='delayu.correspondence')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал регистрации',
            },
        ),
        migrations.CreateModel(
            name='RegistryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('field_schema', models.JSONField(default=list)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_types', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Тип реестра',
                'unique_together': {('subsystem', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RegistryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.organization')),
                ('registry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='delayu.registrytype')),
            ],
            options={
                'verbose_name': 'Запись реестра',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('query_key', models.CharField(max_length=64)),
                ('columns', models.JSONField(default=list)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='delayu.subsystem')),
            ],
            options={
                'unique_together': {('subsystem', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='delayu.reporttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('params', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('kanban_column', models.CharField(choices=[('backlog', 'Очередь'), ('todo', 'К выполнению'), ('in_progress', 'В работе'), ('review', 'Проверка'), ('done', 'Готово')], default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delayu.casefile')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Задача',
                'ordering': ['kanban_column', '-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Назначение в ШР',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('theme_prefs', models.JSONField(blank=True, default=dict)),
                ('active_subsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delayu.subsystem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delayu_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
            },
        ),
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=32)),
                ('code', models.SlugField(max_length=64)),
                ('schema', models.JSONField(default=dict)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_schemas', to='delayu.subsystem')),
            ],
            options={
                'unique_together': {('subsystem', 'target', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LicenseEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delayu.modulecatalog')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='delayu.subsystem')),
            ],
            options={
                'unique_together': {('subsystem', 'module')},
            },
        ),
        migrations.CreateModel(
            name='NSIValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='delayu.nsiclassifier')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delayu.nsivalue')),
            ],
            options={
                'unique_together': {('classifier', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_kind', models.CharField(default='default', max_length=64)),
                ('hours_limit', models.PositiveIntegerField(default=72)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_rules', to='delayu.subsystem')),
            ],
            options={
                'unique_together': {('subsystem', 'case_kind')},
            },
        ),
    ]
