# Generated by Django 5.2.14 on 2026-05-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0002_bpminstance_systemhealthsnapshot_activityevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_registration',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_residence',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подразделение (текст)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dismissal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Личный e-mail'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Табельный/личный №'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(choices=[('staff', 'Штат'), ('contract', 'Договор'), ('part', 'Совместительство'), ('intern', 'Стажёр')], default='staff', max_length=16, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский'), ('u', 'Не указан')], default='u', max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locale',
            field=models.CharField(default='ru', max_length=8, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Сменить пароль при входе'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_series',
            field=models.CharField(blank=True, max_length=8, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_internal',
            field=models.CharField(blank=True, max_length=16, verbose_name='Внутренний'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=32, verbose_name='Мобильный'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_work',
            field=models.CharField(blank=True, max_length=32, verbose_name='Рабочий'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность (текст)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='snils',
            field=models.CharField(blank=True, max_length=14, verbose_name='СНИЛС'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tab_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Табельный номер'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон основной'),
        ),
    ]
