# Generated by Django 5.2.14 on 2026-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0003_userprofile_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='config_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='Версия конфигурации'),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='industry_template',
            field=models.CharField(choices=[('generic', 'Универсальная'), ('municipal', 'Муниципалитет'), ('agency', 'Ведомство'), ('holding', 'Холдинг')], default='generic', max_length=32, verbose_name='Шаблон отрасли'),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
