# Generated by Django 5.2.14 on 2026-05-27 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0004_subsystem_m01_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='Основание / примечание к архиву'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_cases', to=settings.AUTH_USER_MODEL, verbose_name='Кто передал в архив'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='legal_hold',
            field=models.BooleanField(default=False, verbose_name='Legal hold (запрет уничтожения)'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='retention_until',
            field=models.DateField(blank=True, null=True, verbose_name='Срок хранения до'),
        ),
    ]
