# Generated by Django 5.2.14 on 2026-05-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0005_casefile_archive_m06'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='documentfile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='doc_type',
            field=models.CharField(choices=[('attachment', 'Вложение'), ('incoming', 'Входящий'), ('outgoing', 'Исходящий'), ('internal', 'Служебная записка'), ('contract', 'Договор'), ('scan', 'Скан'), ('other', 'Прочее')], default='attachment', max_length=32, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Актуальная версия'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='root_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_chain', to='delayu.documentfile', verbose_name='Корневая версия'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
