# Generated by Django 5.2.14 on 2026-05-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0014_audio_m46_ai_hub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpmtemplate',
            options={'verbose_name': 'Шаблон BPM'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий'},
        ),
        migrations.AlterModelOptions(
            name='integrationendpoint',
            options={'verbose_name': 'Коннектор интеграции'},
        ),
        migrations.AlterModelOptions(
            name='integrationmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение интеграции'},
        ),
        migrations.AlterModelOptions(
            name='slarule',
            options={'verbose_name': 'Правило SLA'},
        ),
        migrations.AlterField(
            model_name='regulatoryreportsubmission',
            name='period_label',
            field=models.CharField(help_text='Напр. 2026-05 или 2026-Q1', max_length=32),
        ),
        migrations.CreateModel(
            name='EtlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('db', 'База данных'), ('api', 'REST API')], default='csv', max_length=16)),
                ('schedule_cron', models.CharField(blank=True, max_length=64, verbose_name='Расписание (cron)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_jobs', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'ETL-задание',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EtlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('success', 'Успех'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('rows_ok', models.PositiveIntegerField(default=0)),
                ('rows_err', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='delayu.etljob')),
            ],
            options={
                'verbose_name': 'Запуск ETL',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#666cff', max_length=16)),
                ('is_visible', models.BooleanField(default=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_layers', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'ГИС-слой',
                'ordering': ['name'],
                'unique_together': {('subsystem', 'code')},
            },
        ),
        migrations.CreateModel(
            name='GeoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_objects', to='delayu.casefile')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='delayu.geolayer')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_objects', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Геообъект',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PwaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_label', models.CharField(max_length=128)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwa_devices', to='delayu.subsystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwa_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PWA-устройство',
                'ordering': ['-last_sync_at', 'device_label'],
            },
        ),
        migrations.CreateModel(
            name='PwaDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='delayu.pwadevice')),
            ],
            options={
                'verbose_name': 'PWA-черновик',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SsoProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('esia', 'ЕСИА'), ('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect')], default='esia', max_length=16)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_providers', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'SSO-провайдер',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CitizenAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=32)),
                ('applicant_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('answered', 'Ответ дан'), ('closed', 'Закрыто')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_appeals', to='delayu.casefile')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_appeals', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Обращение гражданина',
                'ordering': ['-created_at'],
                'unique_together': {('subsystem', 'public_id')},
            },
        ),
        migrations.CreateModel(
            name='DataDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_datasets', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Набор данных',
                'ordering': ['name'],
                'unique_together': {('subsystem', 'slug')},
            },
        ),
    ]
