# Generated by Django 5.2.14 on 2026-05-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0015_infra_m67_m72'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoobject',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_objects', to='delayu.geolayer'),
        ),
    ]
