# Generated by Django 5.2.14 on 2026-05-27 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0016_geo_objects_related_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Выгрузка'},
        ),
        migrations.AlterModelOptions(
            name='formschema',
            options={'ordering': ['target', 'code'], 'verbose_name': 'Схема формы'},
        ),
        migrations.AlterModelOptions(
            name='nsiclassifier',
            options={'ordering': ['name'], 'verbose_name': 'Справочник НСИ'},
        ),
        migrations.AlterModelOptions(
            name='nsivalue',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Значение НСИ'},
        ),
        migrations.AddField(
            model_name='exportjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='records_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formschema',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formschema',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='formschema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nsiclassifier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nsiclassifier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nsivalue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nsivalue',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('success', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='subsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='delayu.subsystem'),
        ),
        migrations.AlterField(
            model_name='formschema',
            name='schema',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='formschema',
            name='target',
            field=models.CharField(choices=[('case', 'Дело'), ('registry', 'Реестр'), ('correspondence', 'Корреспонденция')], default='case', max_length=32),
        ),
        migrations.CreateModel(
            name='BulkOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('status', 'Смена статуса'), ('assign', 'Назначение исполнителя'), ('export', 'Экспорт выборки')], max_length=16)),
                ('target_module', models.CharField(default='M22', max_length=8)),
                ('filter_params', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('success', 'Выполнено'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_operations', to='delayu.subsystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Массовая операция',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('instruction', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('issued', 'Выдано'), ('in_progress', 'В исполнении'), ('done', 'Исполнено'), ('overdue', 'Просрочено')], default='issued', max_length=20)),
                ('report_text', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_directives', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_directives', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directives', to='delayu.casefile')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Поручение',
                'ordering': ['-created_at'],
                'unique_together': {('subsystem', 'number')},
            },
        ),
    ]
