# Generated by Django 5.2.14 on 2026-05-29 11:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0022_mail_transport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystem',
            name='industry_template',
            field=models.CharField(choices=[('generic', 'Универсальная'), ('municipal', 'Муниципалитет'), ('agency', 'Ведомство'), ('holding', 'Холдинг'), ('uzhv', 'АИС УЖВ')], default='generic', max_length=32, verbose_name='Шаблон отрасли'),
        ),
        migrations.CreateModel(
            name='HousingCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('snils', models.CharField(blank=True, db_index=True, max_length=14, verbose_name='СНИЛС')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('reg_address', models.CharField(blank=True, max_length=500, verbose_name='Адрес регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_citizens', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Гражданин (УЖВ)',
                'verbose_name_plural': 'Гражданины (УЖВ)',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MunicipalBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('cadastral_number', models.CharField(blank=True, max_length=64, verbose_name='Кадастровый номер')),
                ('floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('condition', models.CharField(choices=[('ok', 'Исправный'), ('emergency', 'Аварийный'), ('renovation', 'На расселении')], default='ok', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipal_buildings', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'МКД (жилфонд)',
                'verbose_name_plural': 'МКД (жилфонд)',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='MunicipalPremise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='Номер помещения')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площадь, м²')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Комнат')),
                ('status', models.CharField(choices=[('free', 'Свободно'), ('occupied', 'Занято'), ('reserved', 'Резерв')], default='free', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='delayu.municipalbuilding')),
            ],
            options={
                'verbose_name': 'Жилое помещение',
                'verbose_name_plural': 'Жилые помещения',
                'ordering': ['building__address', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='HousingQueueCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=64, verbose_name='Номер дела')),
                ('category', models.CharField(choices=[('general', 'Общая очередь'), ('low_income', 'Малоимущие'), ('young_family', 'Молодые семьи'), ('orphan', 'Дети-сироты'), ('veteran', 'Льготная категория')], default='general', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('registered', 'На учёте'), ('queued', 'В очереди'), ('provided', 'Обеспечен'), ('removed', 'Снят с учёта'), ('rejected', 'Отказ')], default='draft', max_length=20)),
                ('registered_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата постановки на учёт')),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Очерёдность')),
                ('income_verified', models.BooleanField(default=False, verbose_name='Доход проверен')),
                ('low_income_conclusion', models.TextField(blank=True, verbose_name='Заключение о малоимущности')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='delayu.housingcitizen')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_cases', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Учётное дело УЖВ',
                'verbose_name_plural': 'Учётные дела УЖВ',
                'ordering': ['queue_position', '-registered_at'],
                'unique_together': {('subsystem', 'case_number')},
            },
        ),
        migrations.CreateModel(
            name='HousingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=64, verbose_name='Номер')),
                ('contract_type', models.CharField(choices=[('social', 'Социальный найм'), ('special', 'Специализированный'), ('commercial', 'Коммерческий'), ('privatization', 'Приватизация')], max_length=20)),
                ('signed_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заключения')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='delayu.housingcitizen')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_contracts', to='delayu.subsystem')),
                ('premise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='delayu.municipalpremise')),
            ],
            options={
                'verbose_name': 'Договор УЖВ',
                'verbose_name_plural': 'Договоры УЖВ',
                'ordering': ['-signed_at'],
                'unique_together': {('subsystem', 'contract_number')},
            },
        ),
    ]
