# Generated by Django 5.2.14 on 2026-05-29 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0023_uzhv_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='housingqueuecase',
            name='household_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Число членов семьи'),
        ),
        migrations.AddField(
            model_name='housingqueuecase',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Среднемесячный доход, ₽'),
        ),
        migrations.AddField(
            model_name='housingqueuecase',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость имущества, ₽'),
        ),
        migrations.CreateModel(
            name='HousingAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_number', models.CharField(db_index=True, max_length=64, verbose_name='Номер обращения')),
                ('received_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('due_date', models.DateField(verbose_name='Срок ответа')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема')),
                ('body', models.TextField(blank=True, verbose_name='Содержание')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрировано'), ('in_work', 'В работе'), ('answered', 'Ответ дан'), ('closed', 'Закрыто')], default='registered', max_length=20)),
                ('answer_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('answered_at', models.DateField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_appeals_assigned', to=settings.AUTH_USER_MODEL)),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='delayu.housingcitizen')),
                ('correspondence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_appeal', to='delayu.correspondence')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housing_appeals_created', to=settings.AUTH_USER_MODEL)),
                ('housing_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='delayu.housingqueuecase', verbose_name='Учётное дело')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_appeals', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Обращение гражданина',
                'verbose_name_plural': 'Обращения граждан',
                'ordering': ['-received_at', '-appeal_number'],
                'unique_together': {('subsystem', 'appeal_number')},
            },
        ),
    ]
