# Generated by Django 5.2.14 on 2026-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0024_uzhv_appeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingqueuecase',
            name='low_income_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housingqueuecase',
            name='low_income_eligible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Признан малоимущим'),
        ),
        migrations.AddField(
            model_name='housingqueuecase',
            name='per_capita_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Среднедушевой доход, ₽'),
        ),
    ]
