# Generated by Django 5.2.14 on 2026-05-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0025_uzhv_low_income_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanHousingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mintrud_decision_number', models.CharField(blank=True, max_length=64, verbose_name='№ решения Минтруда КК')),
                ('mintrud_decision_date', models.DateField(blank=True, null=True)),
                ('housing_status', models.CharField(choices=[('list_pending', 'Ожидает включения в список'), ('in_list', 'В списке Минтруда'), ('housing', 'Предоставлено жильё'), ('payment', 'Выплата'), ('contract_short', 'Сокращение срока найма')], default='list_pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orphan_record', to='delayu.housingqueuecase')),
            ],
            options={
                'verbose_name': 'Дело дети-сироты',
                'verbose_name_plural': 'Дети-сироты',
            },
        ),
        migrations.CreateModel(
            name='YoungFamilyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_last_name', models.CharField(blank=True, max_length=128, verbose_name='Фамилия супруга(и)')),
                ('spouse_first_name', models.CharField(blank=True, max_length=128, verbose_name='Имя супруга(и)')),
                ('spouse_middle_name', models.CharField(blank=True, max_length=128, verbose_name='Отчество супруга(и)')),
                ('marriage_date', models.DateField(blank=True, null=True, verbose_name='Дата брака')),
                ('children_count', models.PositiveSmallIntegerField(default=0, verbose_name='Детей')),
                ('program', models.CharField(choices=[('jsk', 'Члены ЖСК (2704-КЗ)'), ('economy', 'Жильё экономкласса')], default='jsk', max_length=16)),
                ('meets_criteria', models.BooleanField(default=False, verbose_name='Соответствует критериям')),
                ('notes', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='young_family', to='delayu.housingqueuecase')),
            ],
            options={
                'verbose_name': 'Молодая семья',
                'verbose_name_plural': 'Молодые семьи',
            },
        ),
    ]
