# Generated by Django 5.2.14 on 2026-05-29 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0026_uzhv_programs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalbuilding',
            name='in_resettlement_program',
            field=models.BooleanField(default=False, verbose_name='Программа расселения (4779)'),
        ),
        migrations.AddField(
            model_name='municipalbuilding',
            name='residents_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Численность жителей'),
        ),
        migrations.AddField(
            model_name='municipalbuilding',
            name='total_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая площадь, м²'),
        ),
        migrations.CreateModel(
            name='HousingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(db_index=True, max_length=64, verbose_name='№ проверки')),
                ('inspection_type', models.CharField(choices=[('planned', 'Плановая'), ('unplanned', 'Внеплановая')], default='planned', max_length=16)),
                ('object_type', models.CharField(choices=[('mkd', 'МКД'), ('uk', 'УК'), ('tsj', 'ТСЖ'), ('jsk', 'ЖСК'), ('citizen', 'Гражданин')], default='mkd', max_length=16)),
                ('counterparty_name', models.CharField(blank=True, max_length=255, verbose_name='Объект (УК/ТСЖ/ФИО)')),
                ('check_subject', models.CharField(blank=True, max_length=255, verbose_name='Предмет проверки')),
                ('planned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата проверки')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('in_progress', 'Проводится'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=20)),
                ('result_summary', models.TextField(blank=True, verbose_name='Результаты / акт')),
                ('violations_found', models.BooleanField(default=False, verbose_name='Выявлены нарушения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='delayu.municipalbuilding')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_inspections', to=settings.AUTH_USER_MODEL)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_inspections', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Проверка (жилконтроль)',
                'verbose_name_plural': 'Проверки (жилконтроль)',
                'ordering': ['-planned_date', '-inspection_number'],
                'unique_together': {('subsystem', 'inspection_number')},
            },
        ),
        migrations.CreateModel(
            name='HousingPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(max_length=64, verbose_name='№ предписания')),
                ('issued_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('due_date', models.DateField(verbose_name='Срок устранения')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('status', models.CharField(choices=[('issued', 'Выдано'), ('in_progress', 'Исполняется'), ('fulfilled', 'Исполнено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='issued', max_length=20)),
                ('fulfilled_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='delayu.housinginspection')),
            ],
            options={
                'verbose_name': 'Предписание',
                'verbose_name_plural': 'Предписания',
                'ordering': ['due_date'],
            },
        ),
    ]
