# Generated by Django 5.2.14 on 2026-05-29 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0027_uzhv_inspections'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingCourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=255, verbose_name='Наименование суда')),
                ('case_number', models.CharField(db_index=True, max_length=64, verbose_name='№ дела')),
                ('check_address', models.CharField(blank=True, max_length=500, verbose_name='Адрес проверки')),
                ('defendant_name', models.CharField(blank=True, max_length=255, verbose_name='Ответчик (ФИО/организация)')),
                ('next_hearing_date', models.DateField(blank=True, null=True, verbose_name='Дата заседания')),
                ('ufssp_reference', models.CharField(blank=True, max_length=128, verbose_name='№ ИП (УФССП)')),
                ('status', models.CharField(choices=[('open', 'В производстве'), ('hearing', 'Назначено заседание'), ('decision', 'Решение вынесено'), ('enforcement', 'Исполнительное производство'), ('closed', 'Завершено'), ('cancelled', 'Прекращено')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_cases', to='delayu.housinginspection')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_cases', to='delayu.housingprescription')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_court_cases', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Судебное дело (УЖВ)',
                'verbose_name_plural': 'Судебные дела (УЖВ)',
                'ordering': ['-next_hearing_date', '-case_number'],
                'unique_together': {('subsystem', 'case_number')},
            },
        ),
    ]
