# Generated by Django 5.2.14 on 2026-05-29 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0028_uzhv_court_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingAdminProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(max_length=64, verbose_name='№ протокола')),
                ('protocol_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата составления')),
                ('legal_article', models.CharField(max_length=128, verbose_name='Статья Закона КК / КоАП')),
                ('violator_name', models.CharField(max_length=255, verbose_name='Привлекаемое лицо')),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма штрафа, ₽')),
                ('status', models.CharField(choices=[('draft', 'Проект'), ('issued', 'Составлен'), ('paid', 'Штраф оплачен'), ('appeal', 'Обжалование'), ('cancelled', 'Отменён')], default='issued', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_protocols', to='delayu.housinginspection')),
            ],
            options={
                'verbose_name': 'Протокол об АП',
                'verbose_name_plural': 'Протоколы об АП',
                'ordering': ['-protocol_date', '-protocol_number'],
            },
        ),
        migrations.CreateModel(
            name='HousingInteragencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, max_length=64, verbose_name='№ запроса')),
                ('request_type', models.CharField(choices=[('rosreestr', 'Росреестр / ЕГРН'), ('mvd', 'МВД'), ('zags', 'ЗАГС'), ('fns', 'ФНС'), ('bti', 'БТИ'), ('mintrud', 'Минтруд КК'), ('social', 'Соцзащита / Катарсис'), ('other', 'Иное ведомство')], default='other', max_length=20)),
                ('channel', models.CharField(choices=[('manual', 'Ручной (без интеграции)'), ('smev', 'СМЭВ (не активен)'), ('file', 'Обмен файлом')], default='manual', max_length=16)),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Адресат')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема / основание')),
                ('sent_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('due_date', models.DateField(verbose_name='Срок ответа')),
                ('answered_at', models.DateField(blank=True, null=True)),
                ('response_summary', models.TextField(blank=True, verbose_name='Содержание ответа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('awaiting', 'Ожидает ответа'), ('answered', 'Ответ получен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменён')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interagency_requests', to='delayu.housingcitizen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_interagency_requests', to=settings.AUTH_USER_MODEL)),
                ('housing_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interagency_requests', to='delayu.housingqueuecase')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_interagency_requests', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Межведомственный запрос',
                'verbose_name_plural': 'Межведомственные запросы',
                'ordering': ['-sent_at', '-request_number'],
                'unique_together': {('subsystem', 'request_number')},
            },
        ),
    ]
