# Generated by Django 5.2.14 on 2026-05-31 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0047_uzhv_inspection_conduct_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='housingappeal',
            name='conclusion_kind',
            field=models.CharField(blank=True, choices=[('info', 'Информационный ответ'), ('refusal', 'Отказ'), ('redirect', 'Направление в другой орган'), ('housing', 'Заключение по жилищному вопросу'), ('other', 'Прочее')], max_length=16, verbose_name='Вид заключения'),
        ),
        migrations.AddField(
            model_name='housingappeal',
            name='outgoing_correspondence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_appeal_outgoing', to='delayu.correspondence', verbose_name='Исходящий ответ (M24)'),
        ),
        migrations.CreateModel(
            name='HousingAppealAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('doc_kind', models.CharField(choices=[('incoming', 'Входящее обращение'), ('evidence', 'Подтверждающие документы'), ('outgoing', 'Исходящий ответ'), ('other', 'Прочее')], default='other', max_length=16)),
                ('file', models.FileField(upload_to='uzhv/appeals/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='delayu.housingappeal')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uzhv_appeal_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вложение к обращению',
                'verbose_name_plural': 'Вложения к обращениям',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HousingAppealStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('registered', 'Зарегистрировано'), ('in_work', 'В работе'), ('answered', 'Ответ дан'), ('closed', 'Закрыто')], max_length=20, verbose_name='Было')),
                ('to_status', models.CharField(choices=[('registered', 'Зарегистрировано'), ('in_work', 'В работе'), ('answered', 'Ответ дан'), ('closed', 'Закрыто')], max_length=20, verbose_name='Стало')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delayu.housingappeal')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzhv_appeal_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История статуса обращения',
                'verbose_name_plural': 'История статусов обращений',
                'ordering': ['-changed_at'],
            },
        ),
    ]
