# Generated by Django 5.2.14 on 2026-05-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0048_uzhv_appeals_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinghouseholdmember',
            name='passport_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='housinghouseholdmember',
            name='passport_series',
            field=models.CharField(blank=True, max_length=8, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='housinghouseholdmember',
            name='reg_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='housinghouseholdmember',
            name='snils',
            field=models.CharField(blank=True, max_length=14, verbose_name='СНИЛС'),
        ),
    ]
