# Generated by Django 5.2.16 on 2026-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0067_aipolicy_ai_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystem',
            name='industry_template',
            field=models.CharField(
                choices=[
                    ('generic', 'Универсальная'),
                    ('municipal', 'Муниципалитет'),
                    ('agency', 'Ведомство'),
                    ('holding', 'Холдинг'),
                    ('uzhv', 'АИС УЖВ'),
                    ('fuel', 'Топливный пропуск'),
                    ('invest', 'Инвестконтур'),
                ],
                default='generic',
                max_length=32,
                verbose_name='Шаблон отрасли',
            ),
        ),
    ]
