# Generated by Django 5.2.16 on 2026-07-24 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0068_invest_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('investor_name', models.CharField(blank=True, max_length=255, verbose_name='Инвестор')),
                ('industry', models.CharField(blank=True, max_length=128, verbose_name='Отрасль')),
                ('funnel', models.CharField(choices=[('attraction', 'Привлечение'), ('support', 'Сопровождение')], default='attraction', max_length=16)),
                ('stage', models.CharField(default='lead', max_length=32, verbose_name='Стадия')),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('jobs_count', models.PositiveIntegerField(blank=True, null=True)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invest_projects', to='delayu.organization', verbose_name='МО / территория')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invest_projects_owned', to=settings.AUTH_USER_MODEL)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_projects', to='delayu.subsystem')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('subsystem', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InvestSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=64, verbose_name='Кадастровый номер')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('area_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('land_category', models.CharField(blank=True, max_length=128)),
                ('vri', models.CharField(blank=True, max_length=255, verbose_name='ВРИ')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_review', 'На проверке'), ('actual', 'Актуальный'), ('archived', 'Архив')], default='draft', max_length=16)),
                ('completeness_pct', models.PositiveSmallIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invest_sites', to='delayu.organization')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_sites', to='delayu.subsystem')),
            ],
            options={
                'ordering': ['cadastral_number'],
                'unique_together': {('subsystem', 'cadastral_number')},
            },
        ),
        migrations.CreateModel(
            name='InvestProjectSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('candidate', 'Кандидат'), ('proposed', 'Предложен'), ('booked', 'Забронирован'), ('selected', 'Выбран')], default='candidate', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_links', to='delayu.investproject')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='delayu.investsite')),
            ],
            options={
                'unique_together': {('project', 'site')},
            },
        ),
    ]
