# Generated by Django 5.2.16 on 2026-07-24 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0070_invest_handoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='delayu.investproject')),
            ],
        ),
        migrations.CreateModel(
            name='InvestPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('missing', 'Нет'), ('pending', 'Ожидание'), ('attached', 'Приложено'), ('overdue', 'Просрочено')], default='missing', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='invest/packages/')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delayu.investpackage')),
            ],
        ),
    ]
