# Generated by Django 5.2.16 on 2026-07-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0072_invest_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(blank=True, upload_to='invest/imports/')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('reviewing', 'На проверке'), ('done', 'Завершён')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invest_import_batches', to='delayu.organization')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_import_batches', to='delayu.subsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(choices=[('new_project', 'Новый проект'), ('changed_project', 'Изменён проект'), ('gap', 'Нет в файле'), ('new_site', 'Новая площадка'), ('changed_site', 'Изменена площадка')], max_length=32)),
                ('resolution', models.CharField(choices=[('pending', 'Ожидает'), ('applied', 'Применено'), ('skipped', 'Пропущено')], default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='delayu.investimportbatch')),
                ('target_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='delayu.investproject')),
                ('target_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='delayu.investsite')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
