# Generated by Django 5.2.16 on 2026-07-24 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0073_invest_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investproject',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='investproject',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='investproject',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='investproject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='investproject',
            name='municipality_notes',
            field=models.TextField(blank=True, verbose_name='Комментарий МО'),
        ),
        migrations.AddField(
            model_name='investproject',
            name='planned_end',
            field=models.DateField(blank=True, null=True, verbose_name='План ввода'),
        ),
        migrations.AddField(
            model_name='investproject',
            name='planned_start',
            field=models.DateField(blank=True, null=True, verbose_name='План старта'),
        ),
        migrations.AddField(
            model_name='investproject',
            name='support_measures',
            field=models.TextField(blank=True, verbose_name='Меры поддержки'),
        ),
        migrations.AddField(
            model_name='investsite',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес / местоположение'),
        ),
        migrations.AddField(
            model_name='investsite',
            name='egrn_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Данные ЕГРН обновлены'),
        ),
        migrations.AddField(
            model_name='investsite',
            name='encumbrances',
            field=models.TextField(blank=True, verbose_name='Обременения / ограничения'),
        ),
        migrations.AddField(
            model_name='investsite',
            name='last_smev_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний запрос СМЭВ'),
        ),
        migrations.AddField(
            model_name='investsite',
            name='right_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Вид права'),
        ),
        migrations.AddField(
            model_name='investsite',
            name='zone_info',
            field=models.TextField(blank=True, verbose_name='Зоны / пересечения (черновик)'),
        ),
        migrations.AlterField(
            model_name='integrationendpoint',
            name='endpoint_type',
            field=models.CharField(choices=[('gateway', 'Шлюз'), ('smev', 'СМЭВ'), ('rest', 'REST'), ('external_1c', '1С'), ('external_gis', 'ГИС ЖКХ'), ('mail', 'Почта'), ('webhook', 'Webhook')], max_length=32),
        ),
        migrations.AlterField(
            model_name='investproject',
            name='investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Объём инвестиций, млн руб.'),
        ),
        migrations.AlterField(
            model_name='investproject',
            name='jobs_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рабочие места'),
        ),
        migrations.AlterField(
            model_name='investsite',
            name='area_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Площадь, га'),
        ),
        migrations.AlterField(
            model_name='investsite',
            name='completeness_pct',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Полнота карточки, %'),
        ),
        migrations.AlterField(
            model_name='investsite',
            name='land_category',
            field=models.CharField(blank=True, max_length=128, verbose_name='Категория земель'),
        ),
        migrations.CreateModel(
            name='InvestSmevRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('egrn', 'ЕГРН (кадастр / права)'), ('isogd', 'ИСОГД / ФГИС ТП'), ('rgis', 'РГИС (пересечения)')], default='egrn', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('done', 'Получен ответ'), ('error', 'Ошибка'), ('applied', 'Применено к карточке')], default='queued', max_length=16)),
                ('is_mock', models.BooleanField(default=True, verbose_name='Тестовый контур')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smev_requests', to='delayu.investsite')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_smev_requests', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Запрос СМЭВ (инвест)',
                'verbose_name_plural': 'Запросы СМЭВ (инвест)',
                'ordering': ['-created_at'],
            },
        ),
    ]
