# Generated by Django 5.2.16 on 2026-07-25 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0074_invest_enrich_smev'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('contract_version', models.CharField(default='v1', max_length=16)),
                ('bitrix_webhook_token', models.CharField(blank=True, max_length=128)),
                ('bitrix_api_base', models.URLField(blank=True)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('stage_mapping', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsystem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invest_automation_config', to='delayu.subsystem')),
            ],
        ),
        migrations.CreateModel(
            name='InvestAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_automation_runs', to='delayu.subsystem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestExternalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mo', 'Запрос МО'), ('tp', 'Запрос ТП')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('answered', 'Ответ получен'), ('agreed', 'Согласовано'), ('rejected', 'Отказ'), ('overdue', 'Просрочена'), ('cancelled', 'Отменена')], default='open', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_level', models.PositiveSmallIntegerField(default=0)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invest_external_tasks', to='delayu.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tasks', to='delayu.investproject')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_external_tasks', to='delayu.subsystem')),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestIntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Входящий'), ('out', 'Исходящий')], max_length=8)),
                ('channel', models.CharField(choices=[('bitrix', 'Битрикс24'), ('smev', 'СМЭВ'), ('mo', 'МО'), ('tp', 'ТП'), ('internal', 'Внутренний')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('done', 'Успех'), ('error', 'Ошибка'), ('dead', 'Dead-letter'), ('skipped', 'Пропущено')], default='queued', max_length=16)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to='delayu.investproject')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to='delayu.investsite')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_integration_events', to='delayu.subsystem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subsystem', 'channel', 'status'], name='delayu_inve_subsyst_11d3dc_idx'), models.Index(fields=['external_id', 'event_type'], name='delayu_inve_externa_cfda99_idx')],
            },
        ),
    ]
