# Generated by Django 5.2.16 on 2026-07-25 06:40

import django.db.models.deletion
from django.db import migrations, models
from delayu.migration_ops import AddFieldIfMissing, AddIndexIfMissing, CreateModelIfMissing


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0076_sync_platform_admin_flags'),
    ]

    operations = [
        CreateModelIfMissing(
            name='OdysseusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('base_url', models.URLField(default='http://127.0.0.1:7000')),
                ('embed_mode', models.CharField(choices=[('iframe', 'Iframe'), ('new_tab', 'Новая вкладка'), ('proxy_shell', 'Proxy shell')], default='proxy_shell', max_length=16)),
                ('pinned_ref', models.CharField(blank=True, max_length=128)),
                ('previous_pinned_ref', models.CharField(blank=True, max_length=128)),
                ('upstream_url', models.URLField(blank=True, default='https://github.com/odysseus-dev/odysseus.git')),
                ('vendor_path', models.CharField(default='vendor/odysseus', max_length=255)),
                ('auth_mode', models.CharField(choices=[('none_dev', 'Dev (без auth bridge)'), ('shared_secret', 'Shared secret'), ('header_bridge', 'Header bridge')], default='none_dev', max_length=32)),
                ('shared_secret', models.CharField(blank=True, max_length=255)),
                ('allowed_path_prefixes', models.JSONField(blank=True, default=list)),
                ('timeout_s', models.PositiveSmallIntegerField(default=30)),
                ('role_allowlist', models.JSONField(blank=True, default=list)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_ok', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsystem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odysseus_settings', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Настройки Odysseus',
                'verbose_name_plural': 'Настройки Odysseus',
            },
        ),
    ]
