# Generated by Django 5.2.16 on 2026-07-29 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from delayu.migration_ops import AddFieldIfMissing, AddIndexIfMissing, CreateModelIfMissing


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0089_invest_mnp_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfMissing(
            name='InvestVerificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('investor', 'Инвестор'), ('project', 'Проект'), ('site', 'Площадка')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('done', 'Готово'), ('error', 'Ошибка')], default='queued', max_length=16)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Проверка открытых данных',
                'verbose_name_plural': 'Проверки открытых данных',
                'ordering': ['-created_at'],
            },
        ),
        CreateModelIfMissing(
            name='InvestVerificationSourceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('empty', 'Пусто'), ('error', 'Ошибка'), ('skipped', 'Пропущено')], default='ok', max_length=16)),
                ('severity', models.CharField(choices=[('info', 'Инфо'), ('warn', 'Предупреждение'), ('hard', 'Жёсткий')], default='info', max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('external_url', models.URLField(blank=True, max_length=512)),
                ('error_text', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Результат источника',
                'verbose_name_plural': 'Результаты источников',
                'ordering': ['id'],
            },
        ),
        migrations.RenameIndex(
            model_name='investextract',
            new_name='delayu_inve_subsyst_1d20e3_idx',
            old_name='delayu_inve_subsys_extract_idx',
        ),
        migrations.RenameIndex(
            model_name='investextract',
            new_name='delayu_inve_site_id_ab5535_idx',
            old_name='delayu_inve_site_extract_idx',
        ),
        migrations.RenameIndex(
            model_name='investfgistpdocument',
            new_name='delayu_inve_subsyst_611424_idx',
            old_name='delayu_inve_subsys_fgdoc_idx',
        ),
        migrations.RenameIndex(
            model_name='investfgistpdocument',
            new_name='delayu_inve_level_0127e5_idx',
            old_name='delayu_inve_level_fgdoc_idx',
        ),
        migrations.RenameIndex(
            model_name='investfgistprecord',
            new_name='delayu_inve_subsyst_27c643_idx',
            old_name='delayu_inve_subsys_fgistp_idx',
        ),
        migrations.RenameIndex(
            model_name='investfgistprecord',
            new_name='delayu_inve_site_id_fae0b1_idx',
            old_name='delayu_inve_site_fgistp_idx',
        ),
        migrations.RenameIndex(
            model_name='investmnpfeature',
            new_name='delayu_inve_bbox_mi_4a8e78_idx',
            old_name='delayu_inve_bbox_mi_7c8a1d_idx',
        ),
        migrations.RenameIndex(
            model_name='investmnpfeature',
            new_name='delayu_inve_scheme__b7dea4_idx',
            old_name='delayu_inve_scheme__mnp_cls_idx',
        ),
        AddFieldIfMissing(
            model_name='investverificationrun',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='delayu.investinvestor'),
        ),
        AddFieldIfMissing(
            model_name='investverificationrun',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='delayu.investproject'),
        ),
        AddFieldIfMissing(
            model_name='investverificationrun',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='delayu.investsite'),
        ),
        AddFieldIfMissing(
            model_name='investverificationrun',
            name='subsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_verification_runs', to='delayu.subsystem'),
        ),
        AddFieldIfMissing(
            model_name='investverificationrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfMissing(
            model_name='investverificationsourceresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_results', to='delayu.investverificationrun'),
        ),
        AddIndexIfMissing(
            model_name='investverificationrun',
            index=models.Index(fields=['subsystem', 'target_type', '-created_at'], name='delayu_inve_subsyst_25ed18_idx'),
        ),
        AddIndexIfMissing(
            model_name='investverificationsourceresult',
            index=models.Index(fields=['run', 'source_code'], name='delayu_inve_run_id_ec0624_idx'),
        ),
    ]
