# Generated by Django 5.2.17 on 2026-08-17 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delayu", "0067_aipolicy_ai_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelUfoRegionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('adygea', 'Республика Адыгея'), ('kalmykia', 'Республика Калмыкия'), ('crimea', 'Республика Крым'), ('sevastopol', 'г. Севастополь'), ('krasnodar', 'Краснодарский край'), ('astrakhan', 'Астраханская область'), ('volgograd', 'Волгоградская область'), ('rostov', 'Ростовская область')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Баннер региона ЮФО',
                'verbose_name_plural': 'Баннеры регионов ЮФО',
            },
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_subsystem_admin',
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='industry_template',
            field=models.CharField(choices=[('generic', 'Универсальная'), ('municipal', 'Муниципалитет'), ('agency', 'Ведомство'), ('holding', 'Холдинг'), ('uzhv', 'АИС УЖВ'), ('fuel', 'Топливный пропуск')], default='generic', max_length=32, verbose_name='Шаблон отрасли'),
        ),
        migrations.CreateModel(
            name='FuelUfoAzsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('network', models.CharField(blank=True, default='', max_length=128, verbose_name='Сеть')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
                ('region', models.CharField(choices=[('adygea', 'Республика Адыгея'), ('kalmykia', 'Республика Калмыкия'), ('crimea', 'Республика Крым'), ('sevastopol', 'г. Севастополь'), ('krasnodar', 'Краснодарский край'), ('astrakhan', 'Астраханская область'), ('volgograd', 'Волгоградская область'), ('rostov', 'Ростовская область')], db_index=True, max_length=32, verbose_name='Субъект ЮФО')),
                ('city', models.CharField(blank=True, default='', max_length=128, verbose_name='Город')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('external_sber_id', models.CharField(blank=True, default='', max_length=64)),
                ('external_tbank_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_azs_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ufo_points', to='delayu.fuelazsstation')),
            ],
            options={
                'verbose_name': 'АЗС ЮФО',
                'verbose_name_plural': 'АЗС ЮФО',
                'ordering': ['region', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FuelUfoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_ai92', models.CharField(choices=[('ok', 'Есть'), ('low', 'Мало'), ('empty', 'Нет'), ('unknown', 'Неизвестно')], default='unknown', max_length=16)),
                ('status_ai95', models.CharField(choices=[('ok', 'Есть'), ('low', 'Мало'), ('empty', 'Нет'), ('unknown', 'Неизвестно')], default='unknown', max_length=16)),
                ('status_diesel', models.CharField(choices=[('ok', 'Есть'), ('low', 'Мало'), ('empty', 'Нет'), ('unknown', 'Неизвестно')], default='unknown', max_length=16)),
                ('primary_source', models.CharField(blank=True, choices=[('sber', 'Сбер (партнёр / mock)'), ('tbank', 'Т‑Банк (партнёр / mock)'), ('user', 'Пользователи'), ('azs_operator', 'Оператор АЗС'), ('city_hq', 'Штаб города'), ('yandex_traffic', 'Яндекс.Пробки'), ('manual', 'Ручной ввод')], default='', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('last_reliable_at', models.DateTimeField(blank=True, null=True)),
                ('queue_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('traffic_jams', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Пробки 0–10')),
                ('traffic_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('sources_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('azs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='delayu.fuelufoazspoint')),
            ],
            options={
                'verbose_name': 'Снимок статуса ЮФО',
                'verbose_name_plural': 'Снимки статусов ЮФО',
            },
        ),
        migrations.CreateModel(
            name='FuelUfoSourceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sber', 'Сбер (партнёр / mock)'), ('tbank', 'Т‑Банк (партнёр / mock)'), ('user', 'Пользователи'), ('azs_operator', 'Оператор АЗС'), ('city_hq', 'Штаб города'), ('yandex_traffic', 'Яндекс.Пробки'), ('manual', 'Ручной ввод')], db_index=True, max_length=32)),
                ('fuel_grade', models.CharField(default='ai95', max_length=16, verbose_name='Марка')),
                ('availability', models.CharField(choices=[('ok', 'Есть'), ('low', 'Мало'), ('empty', 'Нет'), ('unknown', 'Неизвестно')], default='unknown', max_length=16)),
                ('queue_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('limit_liters', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cans_allowed', models.BooleanField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('raw_note', models.CharField(blank=True, default='', max_length=512)),
                ('azs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='delayu.fuelufoazspoint')),
            ],
            options={
                'verbose_name': 'Наблюдение ЮФО',
                'verbose_name_plural': 'Наблюдения ЮФО',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelUfoUserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('availability', models.CharField(choices=[('ok', 'Есть'), ('low', 'Мало'), ('empty', 'Нет'), ('unknown', 'Неизвестно')], default='unknown', max_length=16)),
                ('fuel_grade', models.CharField(default='ai95', max_length=16)),
                ('queue_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('limit_liters', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cans_allowed', models.BooleanField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('is_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('azs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to='delayu.fuelufoazspoint')),
            ],
            options={
                'verbose_name': 'Репорт пользователя ЮФО',
                'verbose_name_plural': 'Репорты пользователей ЮФО',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OdysseusSettings',
        ),
        migrations.AddIndex(
            model_name='fuelufoazspoint',
            index=models.Index(fields=['latitude', 'longitude'], name='delayu_fuel_latitud_3ad63b_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelufosourceobservation',
            index=models.Index(fields=['azs', 'source', '-observed_at'], name='delayu_fuel_azs_id_4b1668_idx'),
        ),
    ]
