# Generated by Django 5.2.17 on 2026-09-17 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayu', '0093_merge_invest_ufo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestAiChatTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='Вопрос')),
                ('status', models.CharField(choices=[('requested', 'Запрошена'), ('accepted', 'Принята'), ('joined', 'В чате'), ('closed', 'Закрыта')], db_index=True, default='requested', max_length=16)),
                ('demo_role', models.CharField(blank=True, max_length=64)),
                ('sla_minutes', models.PositiveSmallIntegerField(default=15)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invest_ai_tickets_accepted', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_tickets', to='delayu.investproject')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invest_ai_tickets_requested', to=settings.AUTH_USER_MODEL)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_ai_chat_tickets', to='delayu.subsystem')),
            ],
            options={
                'verbose_name': 'Заявка ИИ-чата специалисту',
                'verbose_name_plural': 'Заявки ИИ-чата специалисту',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subsystem', 'status', '-created_at'], name='delayu_inve_subsyst_9abcf6_idx')],
            },
        ),
    ]
